# Intoduction - Preprocessing

**In this notebook:**
- We load the data from the xlsx file
- We display the data and trying to understand it as best as possible
- We clean the data (fix wrong values, fix NaN values e.t.c)

---

First, we import the python packages that we need.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Loading the data & dataset overview

First, we have to connect to the google drive in order to get access to the xlsx file that contains the data.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Now, we make a dataframe from the file using the pandas package

In [ ]:
my_path = 'DataMining/Assignment/' # type your path to the xlsx file
data_dir = '/content/drive/MyDrive/' + my_path
df = pd.read_excel(data_dir + 'movies.xlsx')

Some columns have spaces at the start and at the end of the name, and some have more than one space between words. This can lead to unexpected errors when trying to retreive data from these columns so we will remove the extra spaces:

In [ ]:
df.rename(columns = lambda x: " ".join(x.split()), inplace = True)

Let's see the first 10 rows:

In [ ]:
df.head(10)

Film  Year            Script Type  \
0                           300  2007             adaptation   
1                  3:10 to Yuma  2007                 remake   
2              30 Days of Night  2007             adaptation   
3           Across the Universe  2007    original screenplay   
4  Alien vs. Predator - Requiem  2007                 sequel   
5       Alvin and the Chipmunks  2007             adaptation   
6             American Gangster  2007  based on a true story   
7                     Bee Movie  2007    original screenplay   
8                       Beowulf  2007    original screenplay   
9               Blades of Glory  2007    original screenplay   

  Rotten Tomatoes critics Metacritic critics Average critics  \
0                      60                 51              56   
1                      88                 76              82   
2                      50                 53              52   
3                      54                 56              55   
4                      14                 29              22   
5                      26                 39              33   
6                      80                 76              78   
7                      52                 54              53   
8                      71                 59              65   
9                      69                 64              67   

   Rotten Tomatoes Audience Metacritic Audience  \
0                      89.0                  71   
1                      86.0                  73   
2                      56.0                  65   
3                      82.0                  73   
4                      31.0                  45   
5                      65.0                  55   
6                      87.0                  75   
7                      53.0                  64   
8                      50.0                  63   
9                      68.0                  70   

  Rotten Tomatoes vs Metacritic deviance Average audience  ...  \
0                                     18               80  ...   
1                                     13               80  ...   
2                                     -9               61  ...   
3                                      9               78  ...   
4                                    -14               38  ...   
5                                     10               60  ...   
6                                     12               81  ...   
7                                    -11               59  ...   
8                                    -13               57  ...   
9                                     -2               69  ...   

  of Gross earned abroad Budget ($million) Budget recovered  \
0                 53.82%                65          701.64%   
1                 23.18%                50          139.56%   
2                 47.31%                32          234.67%   
3                 17.11%                45           65.26%   
4                 67.57%                40          322.21%   
5                 39.71%                70          514.95%   
6                 51.41%               100          267.90%   
7                 55.90%               150          191.42%   
8                 58.12%               150          130.84%   
9                 18.61%                61          238.87%   

  Budget recovered opening weekend  Distributor IMDb Rating  \
0                          109.05%          NaN         NaN   
1                           28.07%          NaN         NaN   
2                           49.85%          NaN         NaN   
3                            8.50%          NaN         NaN   
4                           25.15%          NaN         NaN   
5                           63.30%          NaN         NaN   
6                           43.57%          NaN         NaN   
7                           25.35%          NaN         NaN   
8                           18.34%          NaN         NaN   
9   

some info for the data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1402 entries, 0 to 1401
Data columns (total 31 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Film                                    1402 non-null   object 
 1   Year                                    1402 non-null   int64  
 2   Script Type                             1402 non-null   object 
 3   Rotten Tomatoes critics                 1401 non-null   object 
 4   Metacritic critics                      1402 non-null   object 
 5   Average critics                         1402 non-null   object 
 6   Rotten Tomatoes Audience                1401 non-null   float64
 7   Metacritic Audience                     1402 non-null   object 
 8   Rotten Tomatoes vs Metacritic deviance  1402 non-null   object 
 9   Average audience                        1402 non-null   object 
 10  Audience vs Critics deviance            1402 non-null   obje

---
## Some summary statistics

for numeric values

In [ ]:
df.describe().T

count   mean   std    min    25%    50%    75%  \
Year                       1402.0 2012.1   3.2 2007.0 2009.0 2012.0 2015.0   
Rotten Tomatoes Audience   1401.0   62.1  17.4   17.0   49.0   62.0   76.0   
Opening weekend ($million) 1402.0   23.2  28.5    0.0    6.6   14.2   28.6   
Domestic gross ($million)  1402.0   74.1  87.4    0.0   21.1   44.0   92.6   
Worldwide Gross ($million) 1402.0  173.0 233.9    0.0   38.0   88.7  208.8   
Distributor                   0.0    NaN   NaN    NaN    NaN    NaN    NaN   
IMDb Rating                   0.0    NaN   NaN    NaN    NaN    NaN    NaN   
IMDB vs RT disparity          0.0    NaN   NaN    NaN    NaN    NaN    NaN   

                              max  
Year                       2017.0  
Rotten Tomatoes Audience     98.0  
Opening weekend ($million)  248.0  
Domestic gross ($million)   936.7  
Worldwide Gross ($million) 2781.5  
Distributor                   NaN  
IMDb Rating                   NaN  
IMDB vs RT disparity          NaN

for categorical values (for object type)

In [ ]:
df.describe(include = 'object').T

count unique                    top  \
Film                                    1402   1396            Big Miracle   
Script Type                             1402     17    original screenplay   
Rotten Tomatoes critics                 1401    102                     93   
Metacritic critics                      1402     90                     51   
Average critics                         1402    196                     64   
Metacritic Audience                     1402     78                     66   
Rotten Tomatoes vs Metacritic deviance  1402     82                     -1   
Average audience                        1402    116                     58   
Audience vs Critics deviance            1402     78                     -5   
Primary Genre                             19     11                 comedy   
Genre                                   1401    347                 comedy   
Opening Weekend                         1402   1279                7000000   
Domestic Gross                          1402   1391               20157300   
Foreign Gross ($million)                1402   1268                   0.00   
Foreign Gross                           1402   1308                      0   
Worldwide Gross                         1402   1393              100080000   
of Gross earned abroad                  1402   1230                  0.00%   
Budget ($million)                       1402    192                     20   
Budget recovered                        1402   1365                      -   
Budget recovered opening weekend        1402   1266                      -   
Release Date (US)                       1402    671            Apr 7, 2017   
Oscar Winners                             56      2           Oscar winner   
Oscar Detail                              56     38  Best Animated Feature   

                                       freq  
Film                                      2  
Script Type                             546  
Rotten Tomatoes critics                  29  
Metacritic critics                       39  
Average critics                          25  
Metacritic Audience                      50  
Rotten Tomatoes vs Metacritic deviance   58  
Average audience                         45  
Audience vs Critics deviance             54  
Primary Genre                             5  
Genre                                    98  
Opening Weekend                           4  
Domestic Gross                            2  
Foreign Gross ($million)                 50  
Foreign Gross                            55  
Worldwide Gross                           2  
of Gross earned abroad                   58  
Budget ($million)                        84  
Budget recovered                          6  
Budget recovered opening weekend          6  
Release Date (US)                         7  
Oscar Winners                            36  
Oscar Detail                              7

We can see that some of the object datatypes should not be type of object.

---

# Handling Missing Values

We will take the percentage of missing values for every column.

In [ ]:
def nan_percentage(df):
  missing_data = df.isna().sum()
  # percentage -> (part / whole) * 100
  missing_percentage = (missing_data[missing_data > 0] / df.shape[0]) * 100
  print(missing_percentage)
nan_percentage(df)

Rotten Tomatoes critics      0.1
Rotten Tomatoes Audience     0.1
Primary Genre               98.6
Genre                        0.1
Distributor                100.0
IMDb Rating                100.0
IMDB vs RT disparity       100.0
Oscar Winners               96.0
Oscar Detail                96.0
dtype: float64


- `Rotten Tomatoes critics` & `Rotten Tomatoes Audience` & `Genre`: The missing values for these columns are very few, so we can either use external knowledge to fill these missing values or drop these rows completely.

- `Oscar Winners` & `Oscar Detail`: That means that very few movies have won an Oscar, we have to fix these columns because they are the most important from all the dataset (1 for oscar - 0 for no oscar).

- `Primary Genre`: The missing values in this column are so many that the best option here is to drop the whole column. Like so:

In [ ]:
df = df.drop(columns = ['Primary Genre'])

Now let's look at the `Rotten Tomatoes critics`, `Rotten Tomatos Audience` and `Genre` that seem to have only one missing value in the whole dataset.

In [ ]:
print(df[df['Rotten Tomatoes critics'].isna()][["Film", "Rotten Tomatoes critics", "Rotten Tomatoes Audience"]])

                      Film Rotten Tomatoes critics  Rotten Tomatoes Audience
504  Paranormal Activity 2                     NaN                       NaN


We can see that the missing values for `Rotten Tomatoes critics` and `Rotten Tomatoes Audience` are for the same movie. We have 2 options:

- Drop the row
- find the missing values via external knowledge or from columns that we can extract this information from (i.e. we can find the Rotten Tomatoes critics using the `Average critics` and `Metacritic critics`). Because the movie is only one we can just search on Rotten Tomatoe to fill the missing values

Rotten Tomatoes - Paranormal Activity 2: https://www.rottentomatoes.com/m/paranormal_activity_2  critics: 57 | audience: 48

In [ ]:
df.at[504, 'Rotten Tomatoes critics'], df.at[504, 'Rotten Tomatoes Audience'] = 57, 48

In [ ]:
df.iloc[[504]][["Film", "Rotten Tomatoes critics", "Rotten Tomatoes Audience"]]

Film Rotten Tomatoes critics  Rotten Tomatoes Audience
504  Paranormal Activity 2                      57                      48.0

Let's do the same thing for the one missing value in the Genre column

In [ ]:
df[df['Genre'].isna()][['Film', 'Year', 'Rotten Tomatoes critics']]

Film  Year Rotten Tomatoes critics
930  Deliver Us From Evil  2014                      28


dropping the row with the NaN Genre value

In [ ]:
index = df[df['Genre'].isna()].index
df.drop(index, inplace = True)

Now if we see the NaN percentages again

In [ ]:
nan_percentage(df)

Distributor            100.0
IMDb Rating            100.0
IMDB vs RT disparity   100.0
Oscar Winners           96.0
Oscar Detail            96.0
dtype: float64


We see that the Oscar columns now have a smaller percentage of NaN values because the film that we dropped did not have an oscar (so we also don't lose that much of information)

---

# Handling duplicate films

Let's check if some movies appear more than once in the dataset

In [ ]:
duplicate_movies = df[df.duplicated(subset = ['Film'], keep = False)][['Film', 'Oscar Winners', 'Oscar Detail']]
print(duplicate_movies)

                   Film Oscar Winners                  Oscar Detail
681       That's My Boy           NaN                           NaN
682       That's My Boy           NaN                           NaN
703         Big Miracle           NaN                           NaN
704         Big Miracle           NaN                           NaN
709        Premium Rush           NaN                           NaN
710        Premium Rush           NaN                           NaN
713          The Master           NaN                           NaN
714          The Master           NaN                           NaN
1001  The Good Dinosaur           NaN                           NaN
1062      The Big Short           NaN                           NaN
1135  The Good Dinosaur           NaN                           NaN
1168      The Big Short  Oscar Winner  Writing (adapted screenplay)


We will drop the duplicates of these films, but we have to be careful due to the fact that the film `The Big Short` have different values for the `Oscar Winners` and `Oscar Detail`. We have to verify that the film has an Oscar for best adapted screenplay and if so keep that instance and drop the other one. We follow this strategy because if we drop the row with the oscar winner we lose a lot of information due to the fact that our problem is to find movies that have won an oscar, so we should clean the data and have as many movies with oscar as possible.

We can take the instances that we want to delete by changing the keep argument to 'last'

In [ ]:
duplicate_movies = df[df.duplicated(subset = ['Film'], keep = 'last')][['Film', 'Oscar Winners']]
print(duplicate_movies)

                   Film Oscar Winners
681       That's My Boy           NaN
703         Big Miracle           NaN
709        Premium Rush           NaN
713          The Master           NaN
1001  The Good Dinosaur           NaN
1062      The Big Short           NaN


then we take the indexes of these films and we then drop them

In [ ]:
duplicate_movies = df[df.duplicated(subset = ['Film'], keep = 'last')].index

df.drop(duplicate_movies, inplace = True)

and then we can see that the number of unique films are the same as the number of all the films in the dataset so we now have different films for every row.

In [ ]:
print("total rows: {}".format(df.shape[0]))
print("unique movies: {}".format(df['Film'].nunique()))

total rows: 1395
unique movies: 1395


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1395 entries, 0 to 1401
Data columns (total 30 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Film                                    1395 non-null   object 
 1   Year                                    1395 non-null   int64  
 2   Script Type                             1395 non-null   object 
 3   Rotten Tomatoes critics                 1395 non-null   object 
 4   Metacritic critics                      1395 non-null   object 
 5   Average critics                         1395 non-null   object 
 6   Rotten Tomatoes Audience                1395 non-null   float64
 7   Metacritic Audience                     1395 non-null   object 
 8   Rotten Tomatoes vs Metacritic deviance  1395 non-null   object 
 9   Average audience                        1395 non-null   object 
 10  Audience vs Critics deviance            1395 non-null   obje

---

# Dealing with '-' values

Some of the values in our dataset don't contain information. Instead of the NaN value, Some values have the dash character '-', that means that there is no information.

If we see how many '-' instances are there for each column.

In [ ]:
(df == "-").sum()

Film                                      0
Year                                      0
Script Type                               0
Rotten Tomatoes critics                   1
Metacritic critics                        3
Average critics                           3
Rotten Tomatoes Audience                  0
Metacritic Audience                       2
Rotten Tomatoes vs Metacritic deviance    2
Average audience                          2
Audience vs Critics deviance              4
Genre                                     0
Opening Weekend                           0
Opening weekend ($million)                0
Domestic Gross                            0
Domestic gross ($million)                 0
Foreign Gross ($million)                  0
Foreign Gross                             0
Worldwide Gross                           0
Worldwide Gross ($million)                0
of Gross earned abroad                    0
Budget ($million)                         6
Budget recovered                

Let's see the columns that have to do with budget

In [ ]:
budget_cols = [
	'Budget ($million)',
	'Budget recovered',
	'Budget recovered opening weekend'
]
print(df[df['Budget ($million)'] == '-'][budget_cols + ['Oscar Winners']])

     Budget ($million) Budget recovered Budget recovered opening weekend  \
1272                 -                -                                -   
1325                 -                -                                -   
1367                 -                -                                -   
1375                 -                -                                -   
1388                 -                -                                -   
1401                 -                -                                -   

     Oscar Winners  
1272           NaN  
1325           NaN  
1367           NaN  
1375           NaN  
1388           NaN  
1401           NaN  


We can see that all the missing values for these columns are for the same films. For that reason we drop these rows getting rid of a lot '-' values without losing to much information.

In [ ]:
index_list = df[df['Budget ($million)'] == '-'].index
index_list

Int64Index([1272, 1325, 1367, 1375, 1388, 1401], dtype='int64')

In [ ]:
df.drop(index_list, inplace = True)

In [ ]:
print(df[df['Audience vs Critics deviance'] == '-'][["Rotten Tomatoes Audience", "Metacritic Audience", "Rotten Tomatoes critics", "Metacritic critics", "Average audience", "Average critics"]])

      Rotten Tomatoes Audience Metacritic Audience Rotten Tomatoes critics  \
1268                      87.0                  85                     100   
1317                      78.0                  55                      60   
1322                      63.0                   -                      55   

     Metacritic critics Average audience Average critics  
1268                  -               86               -  
1317                  -               67               -  
1322                 57                -              56  


There are many rows where the values are '-'. That is because some values are a calculation of some other values that are '-'.

If we see all the rows that have '-' for these columns:

In [ ]:
col_ratings = [
      'Average audience',
      'Metacritic Audience',
      'Metacritic critics',
      'Audience vs Critics deviance',
      'Rotten Tomatoes vs Metacritic deviance',
      'Average critics',
]
indexes_drop = set()
for col in col_ratings:
      indexes_drop = indexes_drop.union((df[df[col] == '-'].index).tolist())
print(indexes_drop)

{1322, 1268, 1317}


The rows are only 3. So we could drop them without losing that much information.

In [ ]:
df.drop(indexes_drop, inplace = True)

In [ ]:
(df == "-").sum()

Film                                      0
Year                                      0
Script Type                               0
Rotten Tomatoes critics                   0
Metacritic critics                        0
Average critics                           0
Rotten Tomatoes Audience                  0
Metacritic Audience                       0
Rotten Tomatoes vs Metacritic deviance    0
Average audience                          0
Audience vs Critics deviance              0
Genre                                     0
Opening Weekend                           0
Opening weekend ($million)                0
Domestic Gross                            0
Domestic gross ($million)                 0
Foreign Gross ($million)                  0
Foreign Gross                             0
Worldwide Gross                           0
Worldwide Gross ($million)                0
of Gross earned abroad                    0
Budget ($million)                         0
Budget recovered                

We have cleared all the '-' values

---
We now have to typecast the variables to the correct type

`Opening Weekend`

In [ ]:
try:
  df['Opening Weekend'] = df['Opening Weekend'].astype('str')
except ValueError as error:
  print(error)

In [ ]:
df['Opening Weekend'] = df['Opening Weekend'].apply(lambda x: x.replace(',', ''))

try:
  df['Opening Weekend'] = df['Opening Weekend'].astype('int')
except ValueError as error:
  print(error)

`Rotten Tomatoes critics`

In [ ]:
try:
  df['Rotten Tomatoes critics'] = df['Rotten Tomatoes critics'].astype('int')
except ValueError as error:
  print(error)

`Metacritic critics`

In [ ]:
try:
  df['Metacritic critics'] = df['Metacritic critics'].astype('int')
except ValueError as error:
  print(error)

`Rotten Tomatoes Audience`

In [ ]:
try:
  df["Rotten Tomatoes Audience"] = df["Rotten Tomatoes Audience"].astype('int')
except ValueError as error:
  print(error)

`"Metacritic Audience`

In [ ]:
try:
  df["Metacritic Audience"] = df["Metacritic Audience"].astype('int')
except ValueError as error:
  print(error)

`Rotten Tomatoes vs Metacritic deviance`

In [ ]:
try:
  df["Rotten Tomatoes vs Metacritic deviance"] = df["Rotten Tomatoes vs Metacritic deviance"].astype('int')
except ValueError as error:
  print(error)

`Audience vs Critics deviance`

In [ ]:
try:
  df["Audience vs Critics deviance"] = df["Audience vs Critics deviance"].astype('int')
except ValueError as error:
  print(error)

`Opening Weekend`

In [ ]:
df['Opening Weekend'] = df['Opening Weekend'].astype('str')

df['Opening Weekend'] = df['Opening Weekend'].apply(lambda x: x.replace(',', ''))

try:
  df['Opening Weekend'] = df['Opening Weekend'].astype('int')
except ValueError as error:
  print(error)

`Domestic Gross`

In [ ]:
df["Domestic Gross"] = df["Domestic Gross"].astype('str')

df["Domestic Gross"] = df["Domestic Gross"].apply(lambda x: x.replace(',', ''))

try:
  df["Domestic Gross"] = df["Domestic Gross"].astype('int')
except ValueError as error:
  print(error)

We see that we have a problem converting the `Foreign Gross` column, so let's see which values have the problem and how we are going to deal with them.

In [ ]:
df["Foreign Gross"] = df["Foreign Gross"].astype('str')

df["Foreign Gross"] = df["Foreign Gross"].apply(lambda x: x.replace(',', ''))

try:
  df["Foreign Gross"] = df["Foreign Gross"].astype('int')
except ValueError as error:
  print(error)

invalid literal for int() with base 10: '39.46'


We see that the value that can't be converted contains a dot. Let's see if there is any dot in the rest of the datapoints

In [ ]:
# list that will contain all the values in Foreign Gross containing a dot
fgross_list = []
def check_for_dot(fgross):
  if '.' in str(fgross):
    fgross_list.append(fgross)
    print("foreign gross: {}".format(fgross))

df['Foreign Gross'].apply(check_for_dot)
print(fgross_list)

foreign gross: 39.46
foreign gross: 185465084.00
['39.46', '185465084.00']


We see that there are two values. The first one seems to have the whole information but with a dot followed by 2 zeros. The second one seems to not contain the whole information so we will multiply with 1000000 (we will basically fill the number with zeros)

In [ ]:
for i, fgross in enumerate(fgross_list):
  findex = df[df['Foreign Gross'] == fgross].index.tolist()[0]
  if i == 0: # this means that we have '39.46'
    # remove the dot and multiply it so it is millions
    df.at[findex, 'Foreign Gross'] = str(int(df.at[findex, 'Foreign Gross'].replace('.', '')) * 10000)
  if i == 1: # this means that we have '185465084.00'
    # remove the dot and the following zeros
    df.at[findex, 'Foreign Gross'] = df.at[findex, 'Foreign Gross'].split('.')[0]



Now if we try again:

In [ ]:
df["Foreign Gross"] = df["Foreign Gross"].astype('str')

df["Foreign Gross"] = df["Foreign Gross"].apply(lambda x: x.replace(',', ''))

try:
  df["Foreign Gross"] = df["Foreign Gross"].astype('int')
except ValueError as error:
  print(error)

`Worldwide Gross`

In [ ]:
df["Worldwide Gross"] = df["Worldwide Gross"].astype('str')

df["Worldwide Gross"] = df["Worldwide Gross"].apply(lambda x: x.replace(',', ''))

try:
  df["Worldwide Gross"] = df["Worldwide Gross"].astype('int')
except ValueError as erros:
  print(error)

Now let's see about float values

`Average critics`

In [ ]:
try:
  df['Average critics'] = df['Average critics'].astype('float')
except ValueError as error:
  print(error)

`Average audience`

In [ ]:
try:
  df['Average audience'] = df['Average audience'].astype('float')
except ValueError as error:
  print(error)

`Foreign Gross ($million)`

In [ ]:
try:
  df['Foreign Gross ($million)'] = df['Foreign Gross ($million)'].astype('float')
except ValueError as error:
  print(error)

fgross_mil_list = []
def check_for_comma(fgross_mil):
  if ',' in str(fgross_mil):
    fgross_mil_list.append(fgross_mil)
    print("foreign gross mil: {}".format(fgross_mil))

df['Foreign Gross ($million)'].apply(check_for_comma)
print(fgross_mil_list)

could not convert string to float: '1,162.04'
foreign gross mil: 1,162.04
foreign gross mil: 1,131.56
foreign gross mil: 1,014.00
['1,162.04', '1,131.56', '1,014.00']


Let's see if we can find the values from `Foreign Gross`. Below we cansee that all the values of Foreign Gross are filled so we can just devide this numbers with 1000000.

In [ ]:
for fmil in fgross_mil_list:
  fmindex = df[df['Foreign Gross ($million)'] == fmil].index.tolist()[0]
  print(df.at[fmindex, 'Foreign Gross'])

1162040651
1131561399
1014000000


In [ ]:
for fmil in fgross_mil_list:
  fmindex = df[df['Foreign Gross ($million)'] == fmil].index.tolist()[0]
  df.at[fmindex, 'Foreign Gross ($million)'] = str(int(df.at[fmindex, 'Foreign Gross']) / 1000000)

In [ ]:
try:
  df['Foreign Gross ($million)'] = df['Foreign Gross ($million)'].astype('float')
except ValueError as error:
  print(error)

In [ ]:
(df['Foreign Gross ($million)'] == 0.0).sum()
# (df['Foreign Gross'] == 0.0).sum()

59

We can see that the foreign gross in millions for 15 movies is 0, let's see if we can find something from the `Foreign Gross` column

In [ ]:
df[df['Foreign Gross ($million)'] == 0.0]['Foreign Gross']

191            0
221            0
224            0
636      1001029
813            0
823     39460000
862        69980
952        10949
1028       15084
1029      198116
1039      111460
1040           0
1041     1186027
1042     6185122
1083           0
1091    21434136
1202           0
1239           0
1247           0
1253           0
1254           0
1256           0
1262           0
1270           0
1274           0
1275           0
1280           0
1282           0
1285           0
1292           0
1299           0
1302           0
1304           0
1309           0
1311           0
1315           0
1321           0
1323           0
1324           0
1330           0
1332           0
1333           0
1338           0
1339           0
1341           0
1343           0
1349           0
1351           0
1353           0
1355           0
1359           0
1364           0
1369           0
1374           0
1379           0
1385           0
1387           0
1396           0
1397          

For some values it is zero as well, but for some others there are values that we can fill the `Foreign Gross ($million)` with.

`Budget ($million)`

In [ ]:
try:
  df['Budget ($million)'] = df['Budget ($million)'].astype('float')
except ValueError as error:
  print(error)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1386 entries, 0 to 1400
Data columns (total 30 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Film                                    1386 non-null   object 
 1   Year                                    1386 non-null   int64  
 2   Script Type                             1386 non-null   object 
 3   Rotten Tomatoes critics                 1386 non-null   int64  
 4   Metacritic critics                      1386 non-null   int64  
 5   Average critics                         1386 non-null   float64
 6   Rotten Tomatoes Audience                1386 non-null   int64  
 7   Metacritic Audience                     1386 non-null   int64  
 8   Rotten Tomatoes vs Metacritic deviance  1386 non-null   int64  
 9   Average audience                        1386 non-null   float64
 10  Audience vs Critics deviance            1386 non-null   int6

# Dealing with 0 values

In [ ]:
to_integers = [
    "Rotten Tomatoes critics",
    "Metacritic critics",
    "Rotten Tomatoes Audience",
    "Metacritic Audience",
    "Rotten Tomatoes vs Metacritic deviance",
    "Audience vs Critics deviance",
    "Opening Weekend",
    "Domestic Gross",
    "Foreign Gross",
    "Worldwide Gross" ,
]

for col in to_integers:
  print("{}: {}".format(col, (df[col] == 0).sum()))

Rotten Tomatoes critics: 1
Metacritic critics: 0
Rotten Tomatoes Audience: 0
Metacritic Audience: 0
Rotten Tomatoes vs Metacritic deviance: 56
Audience vs Critics deviance: 18
Opening Weekend: 0
Domestic Gross: 0
Foreign Gross: 49
Worldwide Gross: 0


In [ ]:
(df == 0).sum()

Film                                       0
Year                                       0
Script Type                                0
Rotten Tomatoes critics                    1
Metacritic critics                         0
Average critics                            0
Rotten Tomatoes Audience                   0
Metacritic Audience                        0
Rotten Tomatoes vs Metacritic deviance    56
Average audience                           0
Audience vs Critics deviance              18
Genre                                      0
Opening Weekend                            0
Opening weekend ($million)                 8
Domestic Gross                             0
Domestic gross ($million)                  1
Foreign Gross ($million)                  59
Foreign Gross                             49
Worldwide Gross                            0
Worldwide Gross ($million)                 1
of Gross earned abroad                     0
Budget ($million)                          0
Budget rec

Here we can see that we can fill some values. For example, we see that one value of the `Domestic gross ($million)` column is 0, but the `Domestic Gross` does not have zero values, so we can simply take that value and devide it with 1_000_000.

In [ ]:
print(df[df['Domestic gross ($million)'] == 0][['Domestic gross ($million)', 'Domestic Gross']])
df[df['Domestic gross ($million)'] == 0].index

      Domestic gross ($million)  Domestic Gross
1252                        0.0          355070


Int64Index([1252], dtype='int64')

In [ ]:
df.at[1252, 'Domestic Gross'] / 1000000
df.at[1252, 'Domestic gross ($million)'] = 0.35

In [ ]:
df['Foreign Gross ($million)'] = df['Foreign Gross'] / 1000000

same with Worldwide Gross:

In [ ]:
print(df[df['Worldwide Gross ($million)'] == 0][['Worldwide Gross ($million)', 'Worldwide Gross']])
df[df['Worldwide Gross ($million)'] == 0].index

      Worldwide Gross ($million)  Worldwide Gross
1043                         0.0           398495


Int64Index([1043], dtype='int64')

In [ ]:
df.at[1043, 'Worldwide Gross'] / 1000000
df.at[1043, 'Worldwide Gross ($million)'] = 0.39

In [ ]:
(df == 0).sum()

Film                                       0
Year                                       0
Script Type                                0
Rotten Tomatoes critics                    1
Metacritic critics                         0
Average critics                            0
Rotten Tomatoes Audience                   0
Metacritic Audience                        0
Rotten Tomatoes vs Metacritic deviance    56
Average audience                           0
Audience vs Critics deviance              18
Genre                                      0
Opening Weekend                            0
Opening weekend ($million)                 8
Domestic Gross                             0
Domestic gross ($million)                  0
Foreign Gross ($million)                  49
Foreign Gross                             49
Worldwide Gross                            0
Worldwide Gross ($million)                 0
of Gross earned abroad                     0
Budget ($million)                          0
Budget rec

When it comes to `Audience vs Critics deviance` we do not have a problem with the 18 zero values due to the fact that we can calculate the values of this column using the `Average critics` and `Average audience` columns or due to the fact that the average rating of critics and audience are the same.

In [ ]:
check = df['Average critics'] - df['Average audience']
print((check == df['Audience vs Critics deviance']).sum())

990


We see that some values have noise, so it would be a good idea to calculate the `Audience vs Critics deviance` for all the rows. We also do not want negative values, so we should make it absolute as well.

In [ ]:
df['Audience vs Critics deviance'] = np.abs(df['Average critics'] - df['Average audience'])
df['Audience vs Critics deviance']

0      24.0
1       2.0
2       9.0
3      23.0
4      16.0
       ... 
1396    4.0
1397   11.0
1398    8.0
1399    0.0
1400    1.0
Name: Audience vs Critics deviance, Length: 1386, dtype: float64

Let's now see about the `Rotten Tomatoes vs Metacritic deviance`

In [ ]:
check = df['Rotten Tomatoes Audience'] - df['Metacritic Audience']
print((check == df['Rotten Tomatoes vs Metacritic deviance']).sum())

1383


Let's calculate again, even though in this column the values are accurate, also we will make the values absolute.

In [ ]:
df['Rotten Tomatoes vs Metacritic deviance'] = np.abs(df['Rotten Tomatoes Audience'] - df['Metacritic Audience'])
df['Rotten Tomatoes vs Metacritic deviance']

0       18
1       13
2        9
3        9
4       14
        ..
1396    14
1397     8
1398    14
1399    11
1400    10
Name: Rotten Tomatoes vs Metacritic deviance, Length: 1386, dtype: int64

Now let's handle the one missing value for `Rotten Tomatoes critics`

In [ ]:
df[df['Rotten Tomatoes critics'] == 0][['Rotten Tomatoes critics', 'Metacritic critics', 'Average critics']]

Rotten Tomatoes critics  Metacritic critics  Average critics
201                        0                  24             12.0

Here, 0 is indeed the value (`average critics` = (`Rotten Tomatoes critics` - `Metacritic critics`) / 2) because if we do (24 + 0) / 2 is indeed 12.0

---


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1386 entries, 0 to 1400
Data columns (total 30 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Film                                    1386 non-null   object 
 1   Year                                    1386 non-null   int64  
 2   Script Type                             1386 non-null   object 
 3   Rotten Tomatoes critics                 1386 non-null   int64  
 4   Metacritic critics                      1386 non-null   int64  
 5   Average critics                         1386 non-null   float64
 6   Rotten Tomatoes Audience                1386 non-null   int64  
 7   Metacritic Audience                     1386 non-null   int64  
 8   Rotten Tomatoes vs Metacritic deviance  1386 non-null   int64  
 9   Average audience                        1386 non-null   float64
 10  Audience vs Critics deviance            1386 non-null   floa

---

We can also see that there are wrong values for the `Worldwide Gross` as well and we can see it like so:

In [ ]:
df[df['Worldwide Gross'] < df['Foreign Gross']][['Foreign Gross', 'Worldwide Gross']]

Foreign Gross  Worldwide Gross
849         1800000          1162637
1041        1186027           573335
1091       21434136         12279691
1150      185465084        151288077
1226       31909548         12048652

We can see that for some movies the `Foreign Gross` is greater than the `Worldwide gross`, something that is not possible. So in order to be sure that the Worldwide Gross has the right values, we will recalculate it using the Domestic and the Foreign Gross (addition)

In [ ]:
((df['Foreign Gross'] + df['Domestic Gross']) == df['Worldwide Gross']).sum()

1311

We can also see that the foreign gross plus the domestic gross equals our worldwide gross 1311 times (not all the dataset)

In [ ]:
df['Worldwide Gross'] = df['Foreign Gross'] + df['Domestic Gross']

Now we also have to fix the `Worldwide Gross ($million)

In [ ]:
df['Worldwide Gross ($million)'] = round(df['Worldwide Gross'] / 1000000)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1386 entries, 0 to 1400
Data columns (total 30 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Film                                    1386 non-null   object 
 1   Year                                    1386 non-null   int64  
 2   Script Type                             1386 non-null   object 
 3   Rotten Tomatoes critics                 1386 non-null   int64  
 4   Metacritic critics                      1386 non-null   int64  
 5   Average critics                         1386 non-null   float64
 6   Rotten Tomatoes Audience                1386 non-null   int64  
 7   Metacritic Audience                     1386 non-null   int64  
 8   Rotten Tomatoes vs Metacritic deviance  1386 non-null   int64  
 9   Average audience                        1386 non-null   float64
 10  Audience vs Critics deviance            1386 non-null   floa

In [ ]:
df['of Gross earned abroad'] = df['of Gross earned abroad'].str.replace('%', '')

try:
  df['of Gross earned abroad'] = df['of Gross earned abroad'].astype('float')
except ValueError as error:
  print(error)

In [ ]:
df['Budget recovered'] = df['Budget recovered'].str.replace('%', '')

try:
  df['Budget recovered'] = df['Budget recovered'].astype('float')
except ValueError as error:
  print(error)

In [ ]:
df['Budget recovered opening weekend'] = df['Budget recovered opening weekend'].str.replace('%', '')

try:
  df['Budget recovered opening weekend'] = df['Budget recovered opening weekend'].astype('float')
except ValueError as error:
  print(error)

---

# Dimensionality Reduction

There are some columns that don't provide any information. These columns are either empty or contain little information or they are strongly correlated with another column.

First of all, we have 3 columns that are completely empty (`IMDb Rating`, `IMDB vs RT disparity`, `Distributor`. So we drop these 3 columns.

In [ ]:
df = df.drop(columns = ['IMDb Rating', 'IMDB vs RT disparity', 'Distributor'])

There are columns that do not provide any information. These columns are `Film` and `Oscar Detail`, so we drop these columns.

In [ ]:
df = df.drop(columns = ['Film', 'Oscar Detail'])

In [ ]:
df['of Gross earned abroad'] = df['of Gross earned abroad'].replace('%', '')

try:
  df['of Gross earned abroad'] = df['of Gross earned abroad'].astype('float')
except ValueError as error:
  print(error)

We can also drop the `Release Date (US)` column because we already have the `Year` column so `Release Date (US)` does not provide important information.

In [ ]:
df = df.drop(columns = ['Release Date (US)'])

We can also drop the `Script Type` column:

In [ ]:
df = df.drop(columns = ['Script Type'])

We can also see the correlation between some of the columns:

# Handling Oscar Winners column

We want the value of `Oscar Winners` to be 1 when a movie has won an oscar, 0 otherwise.

In [ ]:
df['Oscar Winners'].unique()

array([nan, 'Oscar winner', 'Oscar Winner'], dtype=object)

We see that the possible values are: nan, 'Oscar winner' and 'Oscar Winner' so we will make the value 1 if the value of the OScar Winners is not nan and 0 otherwise:

In [ ]:
df['Oscar Winners'] = df['Oscar Winners'].notnull().astype('int')

dataframe info:

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1386 entries, 0 to 1400
Data columns (total 23 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Year                                    1386 non-null   int64  
 1   Rotten Tomatoes critics                 1386 non-null   int64  
 2   Metacritic critics                      1386 non-null   int64  
 3   Average critics                         1386 non-null   float64
 4   Rotten Tomatoes Audience                1386 non-null   int64  
 5   Metacritic Audience                     1386 non-null   int64  
 6   Rotten Tomatoes vs Metacritic deviance  1386 non-null   int64  
 7   Average audience                        1386 non-null   float64
 8   Audience vs Critics deviance            1386 non-null   float64
 9   Genre                                   1386 non-null   object 
 10  Opening Weekend                         1386 non-null   int6

In [ ]:
df.head(10)

Year  Rotten Tomatoes critics  Metacritic critics  Average critics  \
0  2007                       60                  51             56.0   
1  2007                       88                  76             82.0   
2  2007                       50                  53             52.0   
3  2007                       54                  56             55.0   
4  2007                       14                  29             22.0   
5  2007                       26                  39             33.0   
6  2007                       80                  76             78.0   
7  2007                       52                  54             53.0   
8  2007                       71                  59             65.0   
9  2007                       69                  64             67.0   

   Rotten Tomatoes Audience  Metacritic Audience  \
0                        89                   71   
1                        86                   73   
2                        56                   65   
3                        82                   73   
4                        31                   45   
5                        65                   55   
6                        87                   75   
7                        53                   64   
8                        50                   63   
9                        68                   70   

   Rotten Tomatoes vs Metacritic deviance  Average audience  \
0                                      18              80.0   
1                                      13              80.0   
2                                       9              61.0   
3                                       9              78.0   
4                                      14              38.0   
5                                      10              60.0   
6                                      12              81.0   
7                                      11              59.0   
8                                      13              57.0   
9                                       2              69.0   

   Audience vs Critics deviance           Genre  ...  \
0                          24.0  period, action  ...   
1                           2.0         western  ...   
2                           9.0          horror  ...   
3                          23.0         musical  ...   
4                          16.0  sci-fi, horror  ...   
5                          27.0  family, comedy  ...   
6                           3.0    crime, drama  ...   
7                           6.0       animation  ...   
8                           8.0       animation  ...   
9                           2.0  sports, comedy  ...   

   Domestic gross ($million)  Foreign Gross ($million)  Foreign Gross  \
0                      210.6                     245.5      245453242   
1                       53.6                      16.2       16173815   
2                       39.6                      35.5       35526091   
3                       24.3                       5.0        5023470   
4                       41.8                      87.1       87086650   
5                      217.3                     143.1      143138914   
6                      130.2                     137.7      137737769   
7                      126.6                     160.5      160492289   
8                       82.2                     114.1      114068876   
9                      118.6                      27.1       27114094   

   Worldwide Gross  Worldwide Gross ($million)  of Gross earned abroad  \
0        456068181                       456.0                    53.8   
1         69780731                        70.0                    23.2   
2         75095087                        75.0                    47.3   
3         29367143                        29.0                    17.1   
4        128883716                       129.0                    67.6   
5        360465888                       360.0                    3

In [ ]:
# stores all the different genres (does not allow duplicates)
genre_set = set()

In [ ]:
def change_genre(df_row):
  genres = df_row['Genre'].lower().replace(" ", "").replace(".", ",").split(',')
  for genre in genres:
    if genre == "":
      continue
    genre_set.add(genre)

In [ ]:
df.apply(change_genre, axis = 1)

0       None
1       None
2       None
3       None
4       None
        ... 
1396    None
1397    None
1398    None
1399    None
1400    None
Length: 1386, dtype: object

Here we can see errors and more seperators more clearly.

For example:

  sci-fi.thriller

  romanticcommedy.

  horro

  famiily

  sport and sports

  thriler and thriller

In [ ]:
genre_set

{'action',
 'adventure',
 'animation',
 'biography',
 'comedy',
 'crime',
 'documentary',
 'drama',
 'famiily',
 'family',
 'fantasy',
 'history',
 'horro',
 'horror',
 'music',
 'musical',
 'mystery',
 'period',
 'romance',
 'romanticcomedy',
 'sci-fi',
 'sport',
 'sports',
 'thriler',
 'thriller',
 'war',
 'western'}

We will replace `horro` with `horror`, `music` with `musical`, `famiily` with `family`, `thriler` with `thriller` and so on for the rest of the wrong genres.

In [ ]:
def handle_genre(df_row):
  genres = df_row['Genre'].lower().replace(" ", "").replace(".", ",").split(',')
  df_row['Genre'] = df_row['Genre'].lower()
  for genre in genres:
    if genre == "":
      continue
    if genre == "horro":
      df_row['Genre'] = df_row['Genre'].replace("horro", "horror")
      genre_set.add("horror")
    elif genre == "famiily":
      df_row['Genre'] = df_row['Genre'].replace("famiily", "family")
      genre_set.add("family")
    elif genre == "music":
      df_row['Genre'] = df_row['Genre'].replace("music", "musical")
      genre_set.add("musical")
    elif genre == "sport":
      df_row['Genre'] = df_row['Genre'].replace("sport", "sports")
      genre_set.add("sports")
    elif genre == "thriler":
      df_row['Genre'] = df_row['Genre'].replace("thriler", "thriller")
      genre_set.add("thriller")
    elif genre == "romanticcomedy":
      df_row['Genre'] = df_row['Genre'].replace("romanticcomedy", "romance, comedy")
      genre_set.add("romance")
      genre_set.add("comedy")
    else:
      genre_set.add(genre)

In [ ]:
genre_set = set()
df.apply(handle_genre, axis = 1)

0       None
1       None
2       None
3       None
4       None
        ... 
1396    None
1397    None
1398    None
1399    None
1400    None
Length: 1386, dtype: object

This list contains all the different genres a movie is.

In [ ]:
list(genre_set)

['action',
 'romance',
 'adventure',
 'animation',
 'western',
 'mystery',
 'comedy',
 'biography',
 'sports',
 'family',
 'thriller',
 'documentary',
 'sci-fi',
 'crime',
 'period',
 'musical',
 'history',
 'fantasy',
 'horror',
 'drama',
 'war']

In [ ]:
genre_df = pd.DataFrame(columns = list(genre_set))
genre_df

Empty DataFrame
Columns: [action, romance, adventure, animation, western, mystery, comedy, biography, sports, family, thriller, documentary, sci-fi, crime, period, musical, history, fantasy, horror, drama, war]
Index: []

[0 rows x 21 columns]

Let's reset the index of our movies dataframe.

In [ ]:
df.index = range(len(df))

Now we create a dataframe with all the different genres as columns.

In [ ]:
genre_df = pd.DataFrame(data = 0, index = np.arange(len(df)), columns = list(genre_set))
genre_df

action  romance  adventure  animation  western  mystery  comedy  \
0          0        0          0          0        0        0       0   
1          0        0          0          0        0        0       0   
2          0        0          0          0        0        0       0   
3          0        0          0          0        0        0       0   
4          0        0          0          0        0        0       0   
...      ...      ...        ...        ...      ...      ...     ...   
1381       0        0          0          0        0        0       0   
1382       0        0          0          0        0        0       0   
1383       0        0          0          0        0        0       0   
1384       0        0          0          0        0        0       0   
1385       0        0          0          0        0        0       0   

      biography  sports  family  ...  documentary  sci-fi  crime  period  \
0             0       0       0  ...            0       0      0       0   
1             0       0       0  ...            0       0      0       0   
2             0       0       0  ...            0       0      0       0   
3             0       0       0  ...            0       0      0       0   
4             0       0       0  ...            0       0      0       0   
...         ...     ...     ...  ...          ...     ...    ...     ...   
1381          0       0       0  ...            0       0      0       0   
1382          0       0       0  ...            0       0      0       0   
1383          0       0       0  ...            0       0      0       0   
1384          0       0       0  ...            0       0      0       0   
1385          0       0       0  ...            0       0      0       0   

      musical  history  fantasy  horror  drama  war  
0           0        0        0       0      0    0  
1           0        0        0       0      0    0  
2           0        0        0       0      0    0  
3           0        0        0       0      0    0  
4           0        0        0       0      0    0  
...       ...      ...      ...     ...    ...  ...  
1381        0        0        0       0      0    0  
1382        0        0        0       0      0    0  
1383        0        0        0       0      0    0  
1384        0        0        0       0      0    0  
1385        0        0        0       0      0    0  

[1386 rows x 21 columns]

In [ ]:
for i, data in df.iterrows():
  genres = df.loc[i, 'Genre'].lower().replace(" ", "").replace(".", ",").split(',')

  for genre in genres:
    if genre == "":
      continue
    if genre == "horro":
      genre_df.loc[i, "horror"] = 1
    elif genre == "famiily":
      genre_df.loc[i, "family"] = 1
    elif genre == "music":
      genre_df.loc[i, "musical"] = 1
    elif genre == "sport":
      genre_df.loc[i, "sports"] = 1
    elif genre == "thriler":
      genre_df.loc[i, "thriller"] = 1
    elif genre == "romanticcomedy":
      genre_df.loc[i, "romance"] = 1
      genre_df.loc[i, "comedy"] = 1
    else:
      genre_df.loc[i, genre] = 1

In [ ]:
genre_df = genre_df.astype(dtype = 'float')

We can now drop the `Genre` column from our dataframe:

In [ ]:
df = df.drop(columns = ['Genre'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 22 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Year                                    1386 non-null   int64  
 1   Rotten Tomatoes critics                 1386 non-null   int64  
 2   Metacritic critics                      1386 non-null   int64  
 3   Average critics                         1386 non-null   float64
 4   Rotten Tomatoes Audience                1386 non-null   int64  
 5   Metacritic Audience                     1386 non-null   int64  
 6   Rotten Tomatoes vs Metacritic deviance  1386 non-null   int64  
 7   Average audience                        1386 non-null   float64
 8   Audience vs Critics deviance            1386 non-null   float64
 9   Opening Weekend                         1386 non-null   int64  
 10  Opening weekend ($million)              1386 non-null   floa

We will now see the correlation between columns in order to see if there are columns in the dataset that don't need to be.

In [ ]:
df.corr().abs()

Year  Rotten Tomatoes critics  \
Year                                     1.0                      0.1   
Rotten Tomatoes critics                  0.1                      1.0   
Metacritic critics                       0.1                      0.9   
Average critics                          0.1                      1.0   
Rotten Tomatoes Audience                 0.1                      0.7   
Metacritic Audience                      0.0                      0.8   
Rotten Tomatoes vs Metacritic deviance   0.0                      0.2   
Average audience                         0.0                      0.8   
Audience vs Critics deviance             0.1                      0.6   
Opening Weekend                          0.0                      0.1   
Opening weekend ($million)               0.0                      0.1   
Domestic Gross                           0.0                      0.2   
Domestic gross ($million)                0.0                      0.2   
Foreign Gross ($million)                 0.1                      0.2   
Foreign Gross                            0.1                      0.2   
Worldwide Gross                          0.0                      0.2   
Worldwide Gross ($million)               0.0                      0.2   
of Gross earned abroad                   0.0                      0.0   
Budget ($million)                        0.0                      0.0   
Budget recovered                         0.0                      0.0   
Budget recovered opening weekend         0.0                      0.0   
Oscar Winners                            0.0                      0.3   

                                        Metacritic critics  Average critics  \
Year                                                   0.1              0.1   
Rotten Tomatoes critics                                0.9              1.0   
Metacritic critics                                     1.0              1.0   
Average critics                                        1.0              1.0   
Rotten Tomatoes Audience                               0.7              0.7   
Metacritic Audience                                    0.8              0.8   
Rotten Tomatoes vs Metacritic deviance                 0.2              0.2   
Average audience                                       0.8              0.8   
Audience vs Critics deviance                           0.5              0.6   
Opening Weekend                                        0.1              0.1   
Opening weekend ($million)                             0.1              0.1   
Domestic Gross                                         0.2              0.2   
Domestic gross ($million)                              0.2              0.2   
Foreign Gross ($million)                               0.2              0.2   
Foreign Gross                                          0.2              0.2   
Worldwide Gross                                        0.2              0.2   
Worldwide Gross ($million)                             0.2              0.2   
of Gross earned abroad                                 0.0              0.0   
Budget ($million)                                      0.0              0.0   
Budget recovered                                       0.0              0.0   
Budget recovered opening weekend                       0.0              0.0   
Oscar Winners                                          0.3              0.3   

                                        Rotten Tomatoes Audience  \
Year                                                         0.1   
Rotten Tomatoes critics                                      0.7   
Metacritic critics                                           0.7   
Average critics                                              0.7   
Rotten Tomatoes Audience                                     1.0   
Metacritic Audience                                          0.7   
Rotten Tomatoes vs Metacritic deviance                       0.2  

We see that all the diferrent critics have a really strong correlation, however we will choose to drop the culomns that have different scales, i.e. Worldwide Gross and Worldwide Gross ($million)

We will drop:

Budget Recovered Opening (corr with Budget recovered: 0.998609)

Worldwide Gross (corr with Worldwide Gross ($million): 0.999999)

Foreign Gross (corr with Foreign Gross ($million): 1.00000)

Domestic Gross (corr with Domestic Gross ($million): 1.00000)

Opening Weekend (corr with Opening Weekend ($million): 0.999998)

For now let's drop these columns:

In [ ]:
df = df.drop(columns = ['Foreign Gross', 'Worldwide Gross', 'Budget recovered opening weekend', 'Domestic Gross', 'Opening Weekend'])

In [ ]:
df.corr().abs()['Average critics']

Year                                     0.1
Rotten Tomatoes critics                  1.0
Metacritic critics                       1.0
Average critics                          1.0
Rotten Tomatoes Audience                 0.7
Metacritic Audience                      0.8
Rotten Tomatoes vs Metacritic deviance   0.2
Average audience                         0.8
Audience vs Critics deviance             0.6
Opening weekend ($million)               0.1
Domestic gross ($million)                0.2
Foreign Gross ($million)                 0.2
Worldwide Gross ($million)               0.2
of Gross earned abroad                   0.0
Budget ($million)                        0.0
Budget recovered                         0.0
Oscar Winners                            0.3
Name: Average critics, dtype: float64

Here we can see that the `Rotten Tomatoes critics` column is strongly correlated with the `Average critics` column 0.99, for that reason we can drop it:

In [ ]:
df = df.drop(columns = ['Rotten Tomatoes critics'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 16 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Year                                    1386 non-null   int64  
 1   Metacritic critics                      1386 non-null   int64  
 2   Average critics                         1386 non-null   float64
 3   Rotten Tomatoes Audience                1386 non-null   int64  
 4   Metacritic Audience                     1386 non-null   int64  
 5   Rotten Tomatoes vs Metacritic deviance  1386 non-null   int64  
 6   Average audience                        1386 non-null   float64
 7   Audience vs Critics deviance            1386 non-null   float64
 8   Opening weekend ($million)              1386 non-null   float64
 9   Domestic gross ($million)               1386 non-null   float64
 10  Foreign Gross ($million)                1386 non-null   floa

Now all that is left in this stage is to normalize the values so that they have the same scale in order to not overfit our model.

We will normalze the values with the min max scaler in order to get the values between 0 and 1.

But before we do that let's extract the `Oscar Winners` column to a seperate dataframe (labels).

In [ ]:
y = df['Oscar Winners']
df = df.drop(columns = ['Oscar Winners'])

In [ ]:
# Normalize the values
df = (df - df.mean()) / df.std()

In [ ]:
df.head(10)

Year  Metacritic critics  Average critics  Rotten Tomatoes Audience  \
0  -1.6                -0.2              0.1                       1.5   
1  -1.6                 1.3              1.3                       1.4   
2  -1.6                -0.0             -0.1                      -0.3   
3  -1.6                 0.1              0.1                       1.1   
4  -1.6                -1.4             -1.4                      -1.8   
5  -1.6                -0.8             -0.9                       0.2   
6  -1.6                 1.3              1.1                       1.4   
7  -1.6                 0.0             -0.0                      -0.5   
8  -1.6                 0.3              0.5                      -0.7   
9  -1.6                 0.6              0.6                       0.3   

   Metacritic Audience  Rotten Tomatoes vs Metacritic deviance  \
0                  0.6                                     1.1   
1                  0.8                                     0.5   
2                  0.2                                    -0.0   
3                  0.8                                    -0.0   
4                 -1.3                                     0.6   
5                 -0.6                                     0.1   
6                  0.9                                     0.3   
7                  0.1                                     0.2   
8                  0.0                                     0.5   
9                  0.5                                    -0.9   

   Average audience  Audience vs Critics deviance  Opening weekend ($million)  \
0               1.2                           1.1                         1.7   
1               1.2                          -1.1                        -0.3   
2              -0.1                          -0.4                        -0.3   
3               1.1                           1.0                        -0.7   
4              -1.7                           0.3                        -0.5   
5              -0.2                           1.4                         0.7   
6               1.3                          -1.0                         0.7   
7              -0.3                          -0.7                         0.5   
8              -0.4                          -0.5                         0.1   
9               0.4                          -1.1                         0.3   

   Domestic gross ($million)  Foreign Gross ($million)  \
0                        1.6                       0.8   
1                       -0.2                      -0.5   
2                       -0.4                      -0.4   
3                       -0.6                      -0.6   
4                       -0.4                      -0.1   
5                        1.6                       0.2   
6                        0.6                       0.2   
7                        0.6                       0.3   
8                        0.1                       0.1   
9                        0.5                      -0.5   

   Worldwide Gross ($million)  of Gross earned abroad  Budget ($million)  \
0                         1.1                     0.3               -0.0   
1                        -0.5                    -1.0               -0.0   
2                        -0.4                     0.0               -0.0   
3                        -0.6                    -1.2               -0.0   
4                        -0.2                     0.9               -0.0   
5                         0.7                    -0.3               -0.0   
6                         0.4                     0.2                0.0   
7                         0.4                     0.4                0.0   
8                         0.1                     0.5                0.0   
9                        -0.1                    -1.1               -0.0   

   Budget recovered  
0              -0.0  
1              -0.0  
2              -0.0  
3    

What left to do now it to concat this dataframe with the dataframe that have the genres.

In [ ]:
genre_df

action  romance  adventure  animation  western  mystery  comedy  \
0        1.0      0.0        0.0        0.0      0.0      0.0     0.0   
1        0.0      0.0        0.0        0.0      1.0      0.0     0.0   
2        0.0      0.0        0.0        0.0      0.0      0.0     0.0   
3        0.0      0.0        0.0        0.0      0.0      0.0     0.0   
4        0.0      0.0        0.0        0.0      0.0      0.0     0.0   
...      ...      ...        ...        ...      ...      ...     ...   
1381     0.0      0.0        0.0        0.0      0.0      0.0     0.0   
1382     0.0      0.0        0.0        0.0      0.0      0.0     0.0   
1383     0.0      0.0        0.0        0.0      0.0      0.0     0.0   
1384     1.0      0.0        1.0        0.0      0.0      0.0     0.0   
1385     1.0      0.0        1.0        0.0      0.0      0.0     0.0   

      biography  sports  family  ...  documentary  sci-fi  crime  period  \
0           0.0     0.0     0.0  ...          0.0     0.0    0.0     1.0   
1           0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
2           0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
3           0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
4           0.0     0.0     0.0  ...          0.0     1.0    0.0     0.0   
...         ...     ...     ...  ...          ...     ...    ...     ...   
1381        0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
1382        0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
1383        0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
1384        0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
1385        0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   

      musical  history  fantasy  horror  drama  war  
0         0.0      0.0      0.0     0.0    0.0  0.0  
1         0.0      0.0      0.0     0.0    0.0  0.0  
2         0.0      0.0      0.0     1.0    0.0  0.0  
3         1.0      0.0      0.0     0.0    0.0  0.0  
4         0.0      0.0      0.0     1.0    0.0  0.0  
...       ...      ...      ...     ...    ...  ...  
1381      0.0      0.0      0.0     0.0    1.0  0.0  
1382      0.0      0.0      0.0     1.0    0.0  0.0  
1383      0.0      0.0      0.0     0.0    1.0  0.0  
1384      0.0      0.0      0.0     0.0    0.0  0.0  
1385      0.0      0.0      0.0     0.0    0.0  0.0  

[1386 rows x 21 columns]

In [ ]:
X = pd.concat([df, genre_df], axis = 1)

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 36 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Year                                    1386 non-null   float64
 1   Metacritic critics                      1386 non-null   float64
 2   Average critics                         1386 non-null   float64
 3   Rotten Tomatoes Audience                1386 non-null   float64
 4   Metacritic Audience                     1386 non-null   float64
 5   Rotten Tomatoes vs Metacritic deviance  1386 non-null   float64
 6   Average audience                        1386 non-null   float64
 7   Audience vs Critics deviance            1386 non-null   float64
 8   Opening weekend ($million)              1386 non-null   float64
 9   Domestic gross ($million)               1386 non-null   float64
 10  Foreign Gross ($million)                1386 non-null   floa

In [ ]:
X.head(10)

Year  Metacritic critics  Average critics  Rotten Tomatoes Audience  \
0  -1.6                -0.2              0.1                       1.5   
1  -1.6                 1.3              1.3                       1.4   
2  -1.6                -0.0             -0.1                      -0.3   
3  -1.6                 0.1              0.1                       1.1   
4  -1.6                -1.4             -1.4                      -1.8   
5  -1.6                -0.8             -0.9                       0.2   
6  -1.6                 1.3              1.1                       1.4   
7  -1.6                 0.0             -0.0                      -0.5   
8  -1.6                 0.3              0.5                      -0.7   
9  -1.6                 0.6              0.6                       0.3   

   Metacritic Audience  Rotten Tomatoes vs Metacritic deviance  \
0                  0.6                                     1.1   
1                  0.8                                     0.5   
2                  0.2                                    -0.0   
3                  0.8                                    -0.0   
4                 -1.3                                     0.6   
5                 -0.6                                     0.1   
6                  0.9                                     0.3   
7                  0.1                                     0.2   
8                  0.0                                     0.5   
9                  0.5                                    -0.9   

   Average audience  Audience vs Critics deviance  Opening weekend ($million)  \
0               1.2                           1.1                         1.7   
1               1.2                          -1.1                        -0.3   
2              -0.1                          -0.4                        -0.3   
3               1.1                           1.0                        -0.7   
4              -1.7                           0.3                        -0.5   
5              -0.2                           1.4                         0.7   
6               1.3                          -1.0                         0.7   
7              -0.3                          -0.7                         0.5   
8              -0.4                          -0.5                         0.1   
9               0.4                          -1.1                         0.3   

   Domestic gross ($million)  ...  documentary  sci-fi  crime  period  \
0                        1.6  ...          0.0     0.0    0.0     1.0   
1                       -0.2  ...          0.0     0.0    0.0     0.0   
2                       -0.4  ...          0.0     0.0    0.0     0.0   
3                       -0.6  ...          0.0     0.0    0.0     0.0   
4                       -0.4  ...          0.0     1.0    0.0     0.0   
5                        1.6  ...          0.0     0.0    0.0     0.0   
6                        0.6  ...          0.0     0.0    1.0     0.0   
7                        0.6  ...          0.0     0.0    0.0     0.0   
8                        0.1  ...          0.0     0.0    0.0     0.0   
9                        0.5  ...          0.0     0.0    0.0     0.0   

   musical  history  fantasy  horror  drama  war  
0      0.0      0.0      0.0     0.0    0.0  0.0  
1      0.0      0.0      0.0     0.0    0.0  0.0  
2      0.0      0.0      0.0     1.0    0.0  0.0  
3      1.0      0.0      0.0     0.0    0.0  0.0  
4      0.0      0.0      0.0     1.0    0.0  0.0  
5      0.0      0.0      0.0     0.0    0.0  0.0  
6      0.0      0.0      0.0     0.0    1.0  0.0  
7      0.0      0.0      0.0     0.0    0.0  0.0  
8      0.0      0.0      0.0     0.0    0.0  0.0  
9      0.0      0.0      0.0     0.0    0.0  0.0  

[10 rows x 36 columns]

In [ ]:
y.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: Oscar Winners, dtype: int64

In [ ]:
# X.to_excel('/content/drive/MyDrive/DataMining/Assignment/train_data.xlsx', index=False)

We are ready to train.

---

### Train

We train various models while experimenting on the Hyperparameters to see how they will go. We need to focus on the recall, we want our model to have as high recall as possible in the oscar winner labels (and obviously the same for non oscar winners).

Let's split our dataset into train set and test set.

In [ ]:
def train(X, y, model):
  '''This function takes the samples and the labels but also the model that will be trained on this data.
     It trains the model 20 times with different splits of the train and test data, calculates the mean of the recall
     for the movie that have won an oscar for all the trainings (20 iterations).

     Note:
        In order for this function to work properly, models should not have a random_state initialized.
  '''

  recall = []
  for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    recall.append(recall_score(y_test, predictions))

  # converts the list to a numpy array and finds the mean, then returns it.
  return np.array(recall).mean(), np.array(recall).std()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import recall_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [ ]:
dtree = DecisionTreeClassifier(criterion='entropy')

In [ ]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
predictions = dtree.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[392   3]
 [ 14   7]]


              precision    recall  f1-score   support

           0       0.97      0.99      0.98       395
           1       0.70      0.33      0.45        21

    accuracy                           0.96       416
   macro avg       0.83      0.66      0.72       416
weighted avg       0.95      0.96      0.95       416



In [ ]:
rec, std = train(X, y, dtree)
print("rec: {} | std: {}".format(rec, std))

rec: 0.3943869855634561 | std: 0.15814744207344864


---

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model=RandomForestClassifier(n_estimators=100, max_depth = None, min_samples_split = 2)

In [ ]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
predictions = model.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

from sklearn.metrics import recall_score
recall_score(y_test, predictions)

[[395   0]
 [ 15   6]]


              precision    recall  f1-score   support

           0       0.96      1.00      0.98       395
           1       1.00      0.29      0.44        21

    accuracy                           0.96       416
   macro avg       0.98      0.64      0.71       416
weighted avg       0.97      0.96      0.95       416



0.2857142857142857

In [ ]:
rec, std = train(X, y, model)
print("rec: {} | std: {}".format(rec, std))

rec: 0.2671522182667693 | std: 0.07779140733713077


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
model_gb = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0)

model_gb.fit(X_train,y_train)

GradientBoostingClassifier(learning_rate=1.0)

In [ ]:
predictions = model_gb.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

from sklearn.metrics import recall_score
recall_score(y_test, predictions)

[[385  10]
 [ 13   8]]


              precision    recall  f1-score   support

           0       0.97      0.97      0.97       395
           1       0.44      0.38      0.41        21

    accuracy                           0.94       416
   macro avg       0.71      0.68      0.69       416
weighted avg       0.94      0.94      0.94       416



0.38095238095238093

In [ ]:
rec, std = train(X, y, model_gb)
print("rec: {} | std: {}".format(rec, std))

rec: 0.36625170881749824 | std: 0.10961630749138555


---

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
model = GaussianNB()

In [ ]:
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
predictions = model.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[138 257]
 [  2  19]]


              precision    recall  f1-score   support

           0       0.99      0.35      0.52       395
           1       0.07      0.90      0.13        21

    accuracy                           0.38       416
   macro avg       0.53      0.63      0.32       416
weighted avg       0.94      0.38      0.50       416



In [ ]:
train(X, y, model)

(0.9268546365914787, 0.053032954549525946)

---

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
model_mlp = MLPClassifier(hidden_layer_sizes = (100, 500,), solver = 'adam', learning_rate_init = 0.0001, max_iter=300)

In [ ]:
model_mlp.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(100, 500), learning_rate_init=0.0001,
              max_iter=300)

In [ ]:
predictions = model_mlp.predict(X_test)

In [ ]:
model_mlp.score(X_test, y_test)

0.9447115384615384

In [ ]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[387   8]
 [ 15   6]]


              precision    recall  f1-score   support

           0       0.96      0.98      0.97       395
           1       0.43      0.29      0.34        21

    accuracy                           0.94       416
   macro avg       0.70      0.63      0.66       416
weighted avg       0.94      0.94      0.94       416



In [ ]:
from sklearn.neighbors import NearestCentroid

In [ ]:
model=NearestCentroid()

In [ ]:
model.fit(X_train,y_train)

NearestCentroid()

In [ ]:
predictions = model.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[298  97]
 [  2  19]]


              precision    recall  f1-score   support

           0       0.99      0.75      0.86       395
           1       0.16      0.90      0.28        21

    accuracy                           0.76       416
   macro avg       0.58      0.83      0.57       416
weighted avg       0.95      0.76      0.83       416



Best models based on result (accuracy and recall) are the DecisionTreeClassifier and MLPClassifier.


---



## Predictions

Let's get the .xlsx file with the unknown movies:

In [ ]:
my_path = 'DataMining/Assignment/' # type your path to the xlsx file
data_dir = '/content/drive/MyDrive/' + my_path
df2 = pd.read_excel(data_dir + 'movies_test _anon.xlsx')

In [ ]:
df2.rename(columns = lambda x: " ".join(x.split()), inplace = True)

In [ ]:
df2

ID Film  Year          Script Type Rotten Tomatoes critics  \
0      1  ???  2019  original screenplay                      73   
1      2  ???  2022                  NaN                      40   
2      3  ???  2019               sequel                      32   
3      4  ???  2022                  NaN                      70   
4      5  ???  2018               remake                      86   
..   ...  ...   ...                  ...                     ...   
560  561  ???  2018  original screenplay                      98   
561  562  ???  2021                  NaN                      72   
562  563  ???  2020           adaptation                      67   
563  564  ???  2021                  NaN                      80   
564  565  ???  2019  original screenplay                      10   

    Metacritic critics Average critics  Rotten Tomatoes Audience  \
0                    -               -                        80   
1                    -              40                        84   
2                   40              36                        94   
3                   60              65                        73   
4                   42              64                        70   
..                 ...             ...                       ...   
560                 90              94                        86   
561                 62              67                        76   
562                 56              62                        71   
563                 50              65                        97   
564                 19              15                        37   

    Metacritic Audience Rotten Tomatoes vs Metacritic deviance  ...  \
0                     -                                      -  ...   
1                     -                                      -  ...   
2                    66                                     28  ...   
3                    66                                      7  ...   
4                    44                                     26  ...   
..                  ...                                    ...  ...   
560                  84                                      2  ...   
561                   -                                      -  ...   
562                  64                                      7  ...   
563                  65                                     32  ...   
564                  42                                     -5  ...   

    Worldwide Gross Worldwide Gross ($million) of Gross earned abroad  \
0          66165510                       66.2                   94.4   
1                 -                          -                      -   
2          21360215                       21.4                      0   
3          21245954                       21.2                    0.6   
4          91244913                        912                    0.4   
..              ...                        ...                    ...   
560        12506396                        125                      -   
561         2244388                        2.2                    NaN   
562             NaN                          -                      -   
563       151403419                      151.4                    NaN   
564         4046429                          4                      0   

    Budget ($million) Budget recovered Budget recovered opening weekend  \
0                  21              3.2                                1   
1                   -                -                                -   
2                  44              0.5                              0.2   
3                  60              0.4                              0.0   
4                  12              7.6                              1.2   
..                ...              ...                              ...   
560              12.5              1.0                              0.0   
561                 -                -    

We have to get thies dataframe to have the same 'shape' as the dataframe that our model was trained with.

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 30 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   ID                                      565 non-null    int64  
 1   Film                                    565 non-null    object 
 2   Year                                    565 non-null    int64  
 3   Script Type                             372 non-null    object 
 4   Rotten Tomatoes critics                 565 non-null    object 
 5   Metacritic critics                      565 non-null    object 
 6   Average critics                         565 non-null    object 
 7   Rotten Tomatoes Audience                565 non-null    int64  
 8   Metacritic Audience                     565 non-null    object 
 9   Rotten Tomatoes vs Metacritic deviance  565 non-null    object 
 10  Average audience                        564 non-null    object

Let's drop some columns that are not needed:

In [ ]:
col_drop = ['Script Type', 'Film', 'Distributor', 'IMDb Rating', 'IMDB vs RT disparity', 'Release Date (US)']
df2 = df2.drop(columns = col_drop)

Let's now check for NaN and '-' values:

In [ ]:
(df2.isna()).sum()

ID                                          0
Year                                        0
Rotten Tomatoes critics                     0
Metacritic critics                          0
Average critics                             0
Rotten Tomatoes Audience                    0
Metacritic Audience                         0
Rotten Tomatoes vs Metacritic deviance      0
Average audience                            1
Audience vs Critics deviance                0
Primary Genre                             306
Genre                                      66
Opening Weekend                             0
Opening weekend ($million)                  0
Domestic Gross                              0
Domestic gross ($million)                   1
Foreign Gross ($million)                  101
Foreign Gross                             101
Worldwide Gross                             3
Worldwide Gross ($million)                  0
of Gross earned abroad                    101
Budget ($million)                 

In [ ]:
(df2 == '-').sum()

ID                                         0
Year                                       0
Rotten Tomatoes critics                    4
Metacritic critics                        15
Average critics                            9
Rotten Tomatoes Audience                   0
Metacritic Audience                       17
Rotten Tomatoes vs Metacritic deviance    17
Average audience                           8
Audience vs Critics deviance              12
Primary Genre                              0
Genre                                     15
Opening Weekend                           13
Opening weekend ($million)                13
Domestic Gross                             4
Domestic gross ($million)                  5
Foreign Gross ($million)                  32
Foreign Gross                             31
Worldwide Gross                           20
Worldwide Gross ($million)                22
of Gross earned abroad                    31
Budget ($million)                         68
Budget rec

We will see if we can get the Genre missing values from the Primary Genre column

We will first replace the '-' values with NaN values.

In [ ]:
df2.replace('-', np.nan, inplace = True)
# there is also one '#VALUE!' in the budget recovered column
df2.replace('#VALUE!', np.nan, inplace = True)

In [ ]:
(df2.isna()).sum()

ID                                          0
Year                                        0
Rotten Tomatoes critics                     4
Metacritic critics                         15
Average critics                             9
Rotten Tomatoes Audience                    0
Metacritic Audience                        17
Rotten Tomatoes vs Metacritic deviance     17
Average audience                            9
Audience vs Critics deviance               12
Primary Genre                             306
Genre                                      81
Opening Weekend                            13
Opening weekend ($million)                 13
Domestic Gross                              4
Domestic gross ($million)                   6
Foreign Gross ($million)                  133
Foreign Gross                             132
Worldwide Gross                            23
Worldwide Gross ($million)                 22
of Gross earned abroad                    132
Budget ($million)                 

In [ ]:
df2[df2['Genre'].isna() & df2['Primary Genre'].isna()]

Empty DataFrame
Columns: [ID, Year, Rotten Tomatoes critics, Metacritic critics, Average critics, Rotten Tomatoes Audience, Metacritic Audience, Rotten Tomatoes vs Metacritic deviance, Average audience, Audience vs Critics deviance, Primary Genre, Genre, Opening Weekend, Opening weekend ($million), Domestic Gross, Domestic gross ($million), Foreign Gross ($million), Foreign Gross, Worldwide Gross, Worldwide Gross ($million), of Gross earned abroad, Budget ($million), Budget recovered, Budget recovered opening weekend]
Index: []

[0 rows x 24 columns]

We can see that they are is no row that Genre and Primary Genre are both NaN. We also saw that Primary Genre does not contain any '-' values. So we are good to take the Primary Genre values and add it to the Genre missing values:

In [ ]:
df2.index = range(len(df2))

In [ ]:
# check if Genre is NaN and if it is insert the value of the Primary Genre of that movie
for i, row in df2.iterrows():
  if pd.isna(df2.at[i, 'Genre']):
    df2.loc[i, 'Genre'] = df2.loc[i, 'Primary Genre']

The Genre column is now filled. Let's move on to other missing values.

---

We see that Domestic Gross ($million) has one NaN value, let's see if we can get it from Domestic Gross column. We will do it for every row.

In [ ]:
df2["Domestic Gross"] = df2["Domestic Gross"].astype('str')

df2["Domestic Gross"] = df2["Domestic Gross"].apply(lambda x: x.replace(',', ''))
df2["Domestic Gross"] = df2["Domestic Gross"].apply(lambda x: x.split('.')[0])

try:
    df2['Domestic Gross'] = df2['Domestic Gross'].astype('float')
except ValueError as error:
  print(error)

In [ ]:
df2["Foreign Gross"] = df2["Foreign Gross"].astype('str')

df2["Foreign Gross"] = df2["Foreign Gross"].apply(lambda x: x.replace(',', ''))
df2["Foreign Gross"] = df2["Foreign Gross"].apply(lambda x: x.split('.')[0])

try:
    df2['Foreign Gross'] = df2['Foreign Gross'].astype('float')
except ValueError as error:
  print(error)

In [ ]:
df2["Worldwide Gross"] = df2["Worldwide Gross"].astype('str')

df2["Worldwide Gross"] = df2["Worldwide Gross"].apply(lambda x: x.replace(',', ''))
df2["Worldwide Gross"] = df2["Worldwide Gross"].apply(lambda x: x.split('.')[0])

try:
  df2["Worldwide Gross"] = df2["Worldwide Gross"].astype('float')
except ValueError as error:
  print(error)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 24 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   ID                                      565 non-null    int64  
 1   Year                                    565 non-null    int64  
 2   Rotten Tomatoes critics                 561 non-null    float64
 3   Metacritic critics                      550 non-null    float64
 4   Average critics                         556 non-null    float64
 5   Rotten Tomatoes Audience                565 non-null    int64  
 6   Metacritic Audience                     548 non-null    float64
 7   Rotten Tomatoes vs Metacritic deviance  548 non-null    float64
 8   Average audience                        556 non-null    float64
 9   Audience vs Critics deviance            553 non-null    float64
 10  Primary Genre                           259 non-null    object

---

calculate the missing value of Worldwide Gross using the Worldwide Gross ($million)

In [ ]:
df2[df2['Worldwide Gross'].isna() & ~df2['Worldwide Gross ($million)'].isna()]

ID  Year  Rotten Tomatoes critics  Metacritic critics  Average critics  \
439  440  2020                     89.0                67.0             78.0   

     Rotten Tomatoes Audience  Metacritic Audience  \
439                        74                 72.0   

     Rotten Tomatoes vs Metacritic deviance  Average audience  \
439                                     2.0              73.0   

     Audience vs Critics deviance  ... Domestic Gross  \
439                           5.0  ...      5200000.0   

    Domestic gross ($million)  Foreign Gross ($million) Foreign Gross  \
439                       NaN                       NaN           NaN   

     Worldwide Gross  Worldwide Gross ($million)  of Gross earned abroad  \
439              NaN                         5.2                     NaN   

     Budget ($million)  Budget recovered  Budget recovered opening weekend  
439                1.0               NaN                               NaN  

[1 rows x 24 columns]

In [ ]:
df2.loc[df2['ID'] == 440, 'Worldwide Gross'] = df2.loc[df2['ID'] == 440, 'Worldwide Gross ($million)'] * 1000000

Now let's continue with handling the Foreign Gross missing values

In [ ]:
fg_cols = ['ID', 'Foreign Gross', 'Foreign Gross ($million)', 'Domestic Gross', 'Domestic gross ($million)', 'Worldwide Gross', 'Worldwide Gross ($million)', 'of Gross earned abroad']
fg = df2[(df2['Foreign Gross'].isna() & df2['Foreign Gross ($million)'].isna())][fg_cols]
fg

ID  Foreign Gross  Foreign Gross ($million)  Domestic Gross  \
1      2            NaN                       NaN       3973263.0   
5      6            NaN                       NaN      48947356.0   
7      8            NaN                       NaN     100916094.0   
11    12            NaN                       NaN       3689637.0   
12    13            NaN                       NaN      29975167.0   
..   ...            ...                       ...             ...   
558  559            NaN                       NaN       1018532.0   
560  561            NaN                       NaN      12506396.0   
561  562            NaN                       NaN       2219760.0   
562  563            NaN                       NaN             NaN   
563  564            NaN                       NaN      40127371.0   

     Domestic gross ($million)  Worldwide Gross  Worldwide Gross ($million)  \
1                          4.0              NaN                         NaN   
5                         48.9       78418101.0                        78.4   
7                        100.9      468043852.0                       468.0   
11                         3.7        5599772.0                         5.6   
12                        30.0       43646976.0                        43.6   
..                         ...              ...                         ...   
558                        1.0              NaN                         NaN   
560                       13.0       12506396.0                       125.0   
561                        2.2        2244388.0                         2.2   
562                        NaN              NaN                         NaN   
563                       40.1      151403419.0                       151.4   

     of Gross earned abroad  
1                       NaN  
5                       NaN  
7                       NaN  
11                      NaN  
12                      NaN  
..                      ...  
558                     NaN  
560                     NaN  
561                     NaN  
562                     NaN  
563                     NaN  

[132 rows x 8 columns]

In [ ]:
fg[~fg['Worldwide Gross'].isna() & ~fg['Domestic Gross'].isna()] # 0 results

ID  Foreign Gross  Foreign Gross ($million)  Domestic Gross  \
5      6            NaN                       NaN      48947356.0   
7      8            NaN                       NaN     100916094.0   
11    12            NaN                       NaN       3689637.0   
12    13            NaN                       NaN      29975167.0   
14    15            NaN                       NaN      17000612.0   
..   ...            ...                       ...             ...   
551  552            NaN                       NaN     213550366.0   
555  556            NaN                       NaN      11338107.0   
560  561            NaN                       NaN      12506396.0   
561  562            NaN                       NaN       2219760.0   
563  564            NaN                       NaN      40127371.0   

     Domestic gross ($million)  Worldwide Gross  Worldwide Gross ($million)  \
5                         48.9       78418101.0                        78.4   
7                        100.9      468043852.0                       468.0   
11                         3.7        5599772.0                         5.6   
12                        30.0       43646976.0                        43.6   
14                        17.0       41909091.0                        41.9   
..                         ...              ...                         ...   
551                      213.6      501546922.0                       501.5   
555                       11.3       37537773.0                        37.5   
560                       13.0       12506396.0                       125.0   
561                        2.2        2244388.0                         2.2   
563                       40.1      151403419.0                       151.4   

     of Gross earned abroad  
5                       NaN  
7                       NaN  
11                      NaN  
12                      NaN  
14                      NaN  
..                      ...  
551                     NaN  
555                     NaN  
560                     NaN  
561                     NaN  
563                     NaN  

[110 rows x 8 columns]

There are 109 rows (out of 132) where we can calcluate the missing values of Foreign Gross (and ($million)). So we can say:

In [ ]:
for i, row in df2.iterrows():
  if pd.isna(df2.at[i, 'Foreign Gross']):
    if not pd.isna(df2.at[i, 'Domestic Gross']) and not pd.isna(df2.at[i, 'Worldwide Gross']): # both of domestic and worldwide gross exist in this row
      # calculate the missing foreign gross
      df2.at[i, 'Foreign Gross'] = df2.at[i, 'Worldwide Gross'] - df2.at[i, 'Domestic Gross']
      df2.at[i, 'Foreign Gross ($million)'] = df2.at[i, 'Foreign Gross'] / 1000000

In [ ]:
(df2.isna()).sum()

ID                                          0
Year                                        0
Rotten Tomatoes critics                     4
Metacritic critics                         15
Average critics                             9
Rotten Tomatoes Audience                    0
Metacritic Audience                        17
Rotten Tomatoes vs Metacritic deviance     17
Average audience                            9
Audience vs Critics deviance               12
Primary Genre                             306
Genre                                       0
Opening Weekend                            13
Opening weekend ($million)                 13
Domestic Gross                              4
Domestic gross ($million)                   6
Foreign Gross ($million)                   23
Foreign Gross                              22
Worldwide Gross                            22
Worldwide Gross ($million)                 22
of Gross earned abroad                    132
Budget ($million)                 

get the new fg dataframe

In [ ]:
fg_cols = ['ID', 'Foreign Gross', 'Foreign Gross ($million)', 'Domestic Gross', 'Domestic gross ($million)', 'Worldwide Gross', 'Worldwide Gross ($million)', 'of Gross earned abroad']
fg = df2[(df2['Foreign Gross'].isna() & df2['Foreign Gross ($million)'].isna())][fg_cols]
fg

ID  Foreign Gross  Foreign Gross ($million)  Domestic Gross  \
1      2            NaN                       NaN       3973263.0   
18    19            NaN                       NaN      26514814.0   
42    43            NaN                       NaN      12668325.0   
67    68            NaN                       NaN       1600542.0   
69    70            NaN                       NaN       4376820.0   
83    84            NaN                       NaN       2561270.0   
93    94            NaN                       NaN      50023780.0   
173  174            NaN                       NaN       4810790.0   
176  177            NaN                       NaN             NaN   
185  186            NaN                       NaN       1170367.0   
216  217            NaN                       NaN       4051990.0   
233  234            NaN                       NaN       2806359.0   
298  299            NaN                       NaN       4509143.0   
338  339            NaN                       NaN             NaN   
351  352            NaN                       NaN       1437938.0   
413  414            NaN                       NaN       1117808.0   
443  444            NaN                       NaN       2893660.0   
453  454            NaN                       NaN      10466091.0   
497  498            NaN                       NaN             NaN   
503  504            NaN                       NaN      15000000.0   
558  559            NaN                       NaN       1018532.0   
562  563            NaN                       NaN             NaN   

     Domestic gross ($million)  Worldwide Gross  Worldwide Gross ($million)  \
1                          4.0              NaN                         NaN   
18                        26.5              NaN                         NaN   
42                        12.7              NaN                         NaN   
67                         1.6              NaN                         NaN   
69                         4.0              NaN                         NaN   
83                         2.6              NaN                         NaN   
93                        50.0              NaN                         NaN   
173                        4.8              NaN                         NaN   
176                        NaN              NaN                         NaN   
185                        1.2              NaN                         NaN   
216                        4.0              NaN                         NaN   
233                        2.8              NaN                         NaN   
298                        4.5              NaN                         NaN   
338                        NaN              NaN                         NaN   
351                        1.4              NaN                         NaN   
413                        1.1              NaN                         NaN   
443                        2.9              NaN                         NaN   
453                       10.5              NaN                         NaN   
497                        NaN              NaN                         NaN   
503                       15.0              NaN                         NaN   
558                        1.0              NaN                         NaN   
562                        NaN              NaN                         NaN   

     of Gross earned abroad  
1                       NaN  
18                      NaN  
42                      NaN  
67                      NaN  
69                      NaN  
83                      NaN  
93                      NaN  
173                     NaN  
176                     NaN  
185                     NaN  
216                     NaN  
233                     NaN  
298                     NaN  
338                     NaN  
351                     NaN  
413                     NaN  
443                     NaN  
453                     NaN  
497                     NaN  


In [ ]:
fg['Domestic Gross'].fillna(value = df2['Domestic Gross'].mean(), inplace = True)
fg['Worldwide Gross'].fillna(value = df2['Worldwide Gross'].mean(), inplace = True)

In [ ]:
pd.options.display.float_format = '{:.1f}'.format
fg['Foreign Gross'] = fg['Worldwide Gross'] - fg['Domestic Gross']
fg

ID  Foreign Gross  Foreign Gross ($million)  Domestic Gross  \
1      2    141638061.8                       NaN       3973263.0   
18    19    119096510.8                       NaN      26514814.0   
42    43    132942999.8                       NaN      12668325.0   
67    68    144010782.8                       NaN       1600542.0   
69    70    141234504.8                       NaN       4376820.0   
83    84    143050054.8                       NaN       2561270.0   
93    94     95587544.8                       NaN      50023780.0   
173  174    140800534.8                       NaN       4810790.0   
176  177     86812823.5                       NaN      58798501.3   
185  186    144440957.8                       NaN       1170367.0   
216  217    141559334.8                       NaN       4051990.0   
233  234    142804965.8                       NaN       2806359.0   
298  299    141102181.8                       NaN       4509143.0   
338  339     86812823.5                       NaN      58798501.3   
351  352    144173386.8                       NaN       1437938.0   
413  414    144493516.8                       NaN       1117808.0   
443  444    142717664.8                       NaN       2893660.0   
453  454    135145233.8                       NaN      10466091.0   
497  498     86812823.5                       NaN      58798501.3   
503  504    130611324.8                       NaN      15000000.0   
558  559    144592792.8                       NaN       1018532.0   
562  563     86812823.5                       NaN      58798501.3   

     Domestic gross ($million)  Worldwide Gross  Worldwide Gross ($million)  \
1                          4.0      145611324.8                         NaN   
18                        26.5      145611324.8                         NaN   
42                        12.7      145611324.8                         NaN   
67                         1.6      145611324.8                         NaN   
69                         4.0      145611324.8                         NaN   
83                         2.6      145611324.8                         NaN   
93                        50.0      145611324.8                         NaN   
173                        4.8      145611324.8                         NaN   
176                        NaN      145611324.8                         NaN   
185                        1.2      145611324.8                         NaN   
216                        4.0      145611324.8                         NaN   
233                        2.8      145611324.8                         NaN   
298                        4.5      145611324.8                         NaN   
338                        NaN      145611324.8                         NaN   
351                        1.4      145611324.8                         NaN   
413                        1.1      145611324.8                         NaN   
443                        2.9      145611324.8                         NaN   
453                       10.5      145611324.8                         NaN   
497                        NaN      145611324.8                         NaN   
503                       15.0      145611324.8                         NaN   
558                        1.0      145611324.8                         NaN   
562                        NaN      145611324.8                         NaN   

     of Gross earned abroad  
1                       NaN  
18                      NaN  
42                      NaN  
67                      NaN  
69                      NaN  
83                      NaN  
93                      NaN  
173                     NaN  
176                     NaN  
185                     NaN  
216                     NaN  
233                     NaN  
298                     NaN  
338                     NaN  
351                     NaN  
413                     NaN  
443                     NaN  
453                     NaN  
497                     NaN  


In [ ]:
for i, row in fg.iterrows():
  id = row['ID']
  df2.loc[df2['ID'] == id, 'Foreign Gross'] = fg.loc[fg['ID'] == id, 'Foreign Gross']

In [ ]:
df2['Foreign Gross'] = df2['Foreign Gross'].astype('int')
df2['Foreign Gross ($million)'] = df2['Foreign Gross'] / 1000000

The Foreign Gross and Foreign Gross ($million) columns are good. Moving on with the rest.

---

In [ ]:
wg_cols = ['ID', 'Worldwide Gross', 'Worldwide Gross ($million)', 'Foreign Gross', 'Foreign Gross ($million)', 'Domestic Gross', 'Domestic gross ($million)', 'of Gross earned abroad']
wg = df2[(df2['Worldwide Gross'].isna() & df2['Worldwide Gross ($million)'].isna())][wg_cols]
wg

ID  Worldwide Gross  Worldwide Gross ($million)  Foreign Gross  \
1      2              NaN                         NaN      141638061   
18    19              NaN                         NaN      119096510   
42    43              NaN                         NaN      132942999   
67    68              NaN                         NaN      144010782   
69    70              NaN                         NaN      141234504   
83    84              NaN                         NaN      143050054   
93    94              NaN                         NaN       95587544   
173  174              NaN                         NaN      140800534   
176  177              NaN                         NaN       86812823   
185  186              NaN                         NaN      144440957   
216  217              NaN                         NaN      141559334   
233  234              NaN                         NaN      142804965   
298  299              NaN                         NaN      141102181   
338  339              NaN                         NaN       86812823   
351  352              NaN                         NaN      144173386   
413  414              NaN                         NaN      144493516   
443  444              NaN                         NaN      142717664   
453  454              NaN                         NaN      135145233   
497  498              NaN                         NaN       86812823   
503  504              NaN                         NaN      130611324   
558  559              NaN                         NaN      144592792   
562  563              NaN                         NaN       86812823   

     Foreign Gross ($million)  Domestic Gross  Domestic gross ($million)  \
1                       141.6       3973263.0                        4.0   
18                      119.1      26514814.0                       26.5   
42                      132.9      12668325.0                       12.7   
67                      144.0       1600542.0                        1.6   
69                      141.2       4376820.0                        4.0   
83                      143.1       2561270.0                        2.6   
93                       95.6      50023780.0                       50.0   
173                     140.8       4810790.0                        4.8   
176                      86.8             NaN                        NaN   
185                     144.4       1170367.0                        1.2   
216                     141.6       4051990.0                        4.0   
233                     142.8       2806359.0                        2.8   
298                     141.1       4509143.0                        4.5   
338                      86.8             NaN                        NaN   
351                     144.2       1437938.0                        1.4   
413                     144.5       1117808.0                        1.1   
443                     142.7       2893660.0                        2.9   
453                     135.1      10466091.0                       10.5   
497                      86.8             NaN                        NaN   
503                     130.6      15000000.0                       15.0   
558                     144.6       1018532.0                        1.0   
562                      86.8             NaN                        NaN   

     of Gross earned abroad  
1                       NaN  
18                      NaN  
42                      NaN  
67                      NaN  
69                      NaN  
83                      NaN  
93                      NaN  
173                     NaN  
176                     NaN  
185                     NaN  
216                     NaN  
233                     NaN  
298                     NaN  
338                     NaN  
351                     NaN  
413                     NaN  
443                     NaN  
453                     NaN  
497                     NaN  


In [ ]:
wg['Domestic Gross'].fillna(value = df2['Domestic Gross'].mean(), inplace = True)
wg['Worldwide Gross'] = wg['Domestic Gross'] + wg['Foreign Gross']
wg

ID  Worldwide Gross  Worldwide Gross ($million)  Foreign Gross  \
1      2      145611324.0                         NaN      141638061   
18    19      145611324.0                         NaN      119096510   
42    43      145611324.0                         NaN      132942999   
67    68      145611324.0                         NaN      144010782   
69    70      145611324.0                         NaN      141234504   
83    84      145611324.0                         NaN      143050054   
93    94      145611324.0                         NaN       95587544   
173  174      145611324.0                         NaN      140800534   
176  177      145611324.3                         NaN       86812823   
185  186      145611324.0                         NaN      144440957   
216  217      145611324.0                         NaN      141559334   
233  234      145611324.0                         NaN      142804965   
298  299      145611324.0                         NaN      141102181   
338  339      145611324.3                         NaN       86812823   
351  352      145611324.0                         NaN      144173386   
413  414      145611324.0                         NaN      144493516   
443  444      145611324.0                         NaN      142717664   
453  454      145611324.0                         NaN      135145233   
497  498      145611324.3                         NaN       86812823   
503  504      145611324.0                         NaN      130611324   
558  559      145611324.0                         NaN      144592792   
562  563      145611324.3                         NaN       86812823   

     Foreign Gross ($million)  Domestic Gross  Domestic gross ($million)  \
1                       141.6       3973263.0                        4.0   
18                      119.1      26514814.0                       26.5   
42                      132.9      12668325.0                       12.7   
67                      144.0       1600542.0                        1.6   
69                      141.2       4376820.0                        4.0   
83                      143.1       2561270.0                        2.6   
93                       95.6      50023780.0                       50.0   
173                     140.8       4810790.0                        4.8   
176                      86.8      58798501.3                        NaN   
185                     144.4       1170367.0                        1.2   
216                     141.6       4051990.0                        4.0   
233                     142.8       2806359.0                        2.8   
298                     141.1       4509143.0                        4.5   
338                      86.8      58798501.3                        NaN   
351                     144.2       1437938.0                        1.4   
413                     144.5       1117808.0                        1.1   
443                     142.7       2893660.0                        2.9   
453                     135.1      10466091.0                       10.5   
497                      86.8      58798501.3                        NaN   
503                     130.6      15000000.0                       15.0   
558                     144.6       1018532.0                        1.0   
562                      86.8      58798501.3                        NaN   

     of Gross earned abroad  
1                       NaN  
18                      NaN  
42                      NaN  
67                      NaN  
69                      NaN  
83                      NaN  
93                      NaN  
173                     NaN  
176                     NaN  
185                     NaN  
216                     NaN  
233                     NaN  
298                     NaN  
338                     NaN  
351                     NaN  
413                     NaN  
443                     NaN  
453                     NaN  
497                     NaN  


In [ ]:
for i, row in wg.iterrows():
  id = row['ID']
  df2.loc[df2['ID'] == id, 'Worldwide Gross'] = wg.loc[wg['ID'] == id, 'Worldwide Gross']

In [ ]:
df2['Worldwide Gross'] = df2['Worldwide Gross'].astype('int')
df2['Worldwide Gross ($million)'] = df2['Worldwide Gross'] / 1000000

---

In [ ]:
df2[~df2['Domestic Gross'].isna() & df2['Domestic gross ($million)'].isna()]

ID  Year  Rotten Tomatoes critics  Metacritic critics  Average critics  \
439  440  2020                     89.0                67.0             78.0   
547  548  2018                     87.0                83.0             85.0   

     Rotten Tomatoes Audience  Metacritic Audience  \
439                        74                 72.0   
547                        72                 69.0   

     Rotten Tomatoes vs Metacritic deviance  Average audience  \
439                                     2.0              73.0   
547                                     3.0              71.0   

     Audience vs Critics deviance  ... Domestic Gross  \
439                           5.0  ...      5200000.0   
547                          15.0  ...     81903458.0   

    Domestic gross ($million)  Foreign Gross ($million) Foreign Gross  \
439                       NaN                       0.0             0   
547                       NaN                      95.8      95766894   

     Worldwide Gross  Worldwide Gross ($million)  of Gross earned abroad  \
439          5200000                         5.2                     NaN   
547        177670352                       177.7                     0.5   

     Budget ($million)  Budget recovered  Budget recovered opening weekend  
439                1.0               NaN                               NaN  
547               50.0               3.6                               0.4  

[2 rows x 24 columns]

In [ ]:
df2.loc[df2['ID'] == 440, 'Domestic gross ($million)'] = df2.loc[df2['ID'] == 440, 'Domestic Gross'] / 1000000
df2.loc[df2['ID'] == 548, 'Domestic gross ($million)'] = df2.loc[df2['ID'] == 548, 'Domestic Gross'] / 1000000

In [ ]:
dg_cols = ['ID', 'Domestic Gross', 'Domestic gross ($million)', 'Foreign Gross', 'Foreign Gross ($million)', 'Worldwide Gross', 'Worldwide Gross ($million)', 'of Gross earned abroad']
dg = df2[(df2['Domestic Gross'].isna() & df2['Domestic gross ($million)'].isna())][dg_cols]
dg

ID  Domestic Gross  Domestic gross ($million)  Foreign Gross  \
176  177             NaN                        NaN       86812823   
338  339             NaN                        NaN       86812823   
497  498             NaN                        NaN       86812823   
562  563             NaN                        NaN       86812823   

     Foreign Gross ($million)  Worldwide Gross  Worldwide Gross ($million)  \
176                      86.8        145611324                       145.6   
338                      86.8        145611324                       145.6   
497                      86.8        145611324                       145.6   
562                      86.8        145611324                       145.6   

     of Gross earned abroad  
176                     NaN  
338                     NaN  
497                     NaN  
562                     NaN

In [ ]:
dg['Domestic Gross'] = dg['Worldwide Gross'] - dg['Foreign Gross']
dg

ID  Domestic Gross  Domestic gross ($million)  Foreign Gross  \
176  177        58798501                        NaN       86812823   
338  339        58798501                        NaN       86812823   
497  498        58798501                        NaN       86812823   
562  563        58798501                        NaN       86812823   

     Foreign Gross ($million)  Worldwide Gross  Worldwide Gross ($million)  \
176                      86.8        145611324                       145.6   
338                      86.8        145611324                       145.6   
497                      86.8        145611324                       145.6   
562                      86.8        145611324                       145.6   

     of Gross earned abroad  
176                     NaN  
338                     NaN  
497                     NaN  
562                     NaN

In [ ]:
for i, row in dg.iterrows():
  id = row['ID']
  df2.loc[df2['ID'] == id, 'Domestic Gross'] = dg.loc[dg['ID'] == id, 'Domestic Gross']

In [ ]:
df2['Domestic Gross'] = df2['Domestic Gross'].astype('int')
df2['Domestic gross ($million)'] = df2['Domestic Gross'] / 1000000

---

We have calculates the missing values of Domestic, Foreign and Worldwide gross ($million). Now let's calculate the missing values of `of Gross earned abroad`

In [ ]:
ga_cols = ['ID', 'Worldwide Gross ($million)', 'Foreign Gross ($million)', 'of Gross earned abroad']
ga = df2[df2['of Gross earned abroad'].isna()][ga_cols]
ga

ID  Worldwide Gross ($million)  Foreign Gross ($million)  \
1      2                       145.6                     141.6   
5      6                        78.4                      29.5   
7      8                       468.0                     367.1   
11    12                         5.6                       1.9   
12    13                        43.6                      13.7   
..   ...                         ...                       ...   
558  559                       145.6                     144.6   
560  561                        12.5                       0.0   
561  562                         2.2                       0.0   
562  563                       145.6                      86.8   
563  564                       151.4                     111.3   

     of Gross earned abroad  
1                       NaN  
5                       NaN  
7                       NaN  
11                      NaN  
12                      NaN  
..                      ...  
558                     NaN  
560                     NaN  
561                     NaN  
562                     NaN  
563                     NaN  

[132 rows x 4 columns]

In [ ]:
ga['of Gross earned abroad'] = (ga['Foreign Gross ($million)'] / ga['Worldwide Gross ($million)']) * 100
ga

ID  Worldwide Gross ($million)  Foreign Gross ($million)  \
1      2                       145.6                     141.6   
5      6                        78.4                      29.5   
7      8                       468.0                     367.1   
11    12                         5.6                       1.9   
12    13                        43.6                      13.7   
..   ...                         ...                       ...   
558  559                       145.6                     144.6   
560  561                        12.5                       0.0   
561  562                         2.2                       0.0   
562  563                       145.6                      86.8   
563  564                       151.4                     111.3   

     of Gross earned abroad  
1                      97.3  
5                      37.6  
7                      78.4  
11                     34.1  
12                     31.3  
..                      ...  
558                    99.3  
560                     0.0  
561                     1.1  
562                    59.6  
563                    73.5  

[132 rows x 4 columns]

In [ ]:
for i, row in ga.iterrows():
  id = row['ID']
  df2.loc[df2['ID'] == id, 'of Gross earned abroad'] = ga.loc[ga['ID'] == id, 'of Gross earned abroad']

---

Let's handle Opening Weekend missing values

In [ ]:
df2[df2['Opening Weekend'].isna()][['Opening Weekend', 'Opening weekend ($million)']]

Opening Weekend Opening weekend ($million)
24               NaN                        NaN
74               NaN                        NaN
176              NaN                        NaN
185              NaN                        NaN
311              NaN                        NaN
338              NaN                        NaN
355              NaN                        NaN
404              NaN                        NaN
439              NaN                        NaN
470              NaN                        NaN
497              NaN                        NaN
503              NaN                        NaN
562              NaN                        NaN

In this situation we do not have any values that we can calculate Opening Weekend with so we are going to use the mean of the column.

In [ ]:
df2['Opening Weekend'].fillna(value = df2['Opening Weekend'].mean(), inplace = True)
df2['Opening weekend ($million)'] = df2['Opening Weekend'] / 1000000

---

Let's handle the critics columns

In [ ]:
critics_cols = ['Metacritic critics', 'Rotten Tomatoes critics', 'Average critics', 'Rotten Tomatoes vs Metacritic deviance', 'Average audience']
df2[df2['Metacritic critics'].isna()][critics_cols]

Metacritic critics  Rotten Tomatoes critics  Average critics  \
0                   NaN                     73.0              NaN   
1                   NaN                     40.0             40.0   
24                  NaN                      0.0              0.0   
74                  NaN                      NaN              NaN   
109                 NaN                     86.0              NaN   
185                 NaN                      NaN              NaN   
216                 NaN                     58.0              NaN   
284                 NaN                     22.0              NaN   
298                 NaN                      7.0              7.0   
311                 NaN                      0.0              0.0   
317                 NaN                     40.0             40.0   
413                 NaN                      NaN              NaN   
415                 NaN                      0.0              0.0   
442                 NaN                     33.0              NaN   
443                 NaN                     17.0             17.0   

     Rotten Tomatoes vs Metacritic deviance  Average audience  
0                                       NaN               NaN  
1                                       NaN              84.0  
24                                      6.0               5.0  
74                                      NaN              89.0  
109                                     NaN               NaN  
185                                     NaN             100.0  
216                                     3.0              85.0  
284                                     NaN               NaN  
298                                   -17.0              44.0  
311                                    49.0              68.0  
317                                     NaN              93.0  
413                                     NaN               NaN  
415                                     NaN              36.0  
442                                     NaN               NaN  
443                                     NaN              50.0

In [ ]:
df2[df2['Average critics'].isna()][critics_cols]

Metacritic critics  Rotten Tomatoes critics  Average critics  \
0                   NaN                     73.0              NaN   
74                  NaN                      NaN              NaN   
109                 NaN                     86.0              NaN   
185                 NaN                      NaN              NaN   
216                 NaN                     58.0              NaN   
284                 NaN                     22.0              NaN   
413                 NaN                      NaN              NaN   
442                 NaN                     33.0              NaN   
447                79.0                      NaN              NaN   

     Rotten Tomatoes vs Metacritic deviance  Average audience  
0                                       NaN               NaN  
74                                      NaN              89.0  
109                                     NaN               NaN  
185                                     NaN             100.0  
216                                     3.0              85.0  
284                                     NaN               NaN  
413                                     NaN               NaN  
442                                     NaN               NaN  
447                                   -34.0              37.0

---

In [ ]:
(df2.isna()).sum()

ID                                          0
Year                                        0
Rotten Tomatoes critics                     4
Metacritic critics                         15
Average critics                             9
Rotten Tomatoes Audience                    0
Metacritic Audience                        17
Rotten Tomatoes vs Metacritic deviance     17
Average audience                            9
Audience vs Critics deviance               12
Primary Genre                             306
Genre                                       0
Opening Weekend                             0
Opening weekend ($million)                  0
Domestic Gross                              0
Domestic gross ($million)                   0
Foreign Gross ($million)                    0
Foreign Gross                               0
Worldwide Gross                             0
Worldwide Gross ($million)                  0
of Gross earned abroad                      0
Budget ($million)                 

---

audience columns

Let's see if we can calculate some missing values of the Metacritic Audience

In [ ]:
audience_cols = [
    'ID',
    'Rotten Tomatoes Audience',
    'Metacritic Audience',
    'Average audience',
    'Rotten Tomatoes critics',
    'Metacritic critics',
    'Average critics',
    'Rotten Tomatoes vs Metacritic deviance',
    'Audience vs Critics deviance']
df2[df2['Metacritic Audience'].isna()][audience_cols]

ID  Rotten Tomatoes Audience  Metacritic Audience  Average audience  \
0      1                        80                  NaN               NaN   
1      2                        84                  NaN              84.0   
54    55                        71                  NaN               NaN   
74    75                        89                  NaN              89.0   
103  104                        39                  NaN               NaN   
109  110                        70                  NaN               NaN   
185  186                       100                  NaN             100.0   
284  285                        29                  NaN               NaN   
315  316                        81                  NaN              81.0   
317  318                        93                  NaN              93.0   
413  414                        79                  NaN               NaN   
415  416                        36                  NaN              36.0   
442  443                        58                  NaN               NaN   
443  444                        50                  NaN              50.0   
477  478                        87                  NaN               NaN   
558  559                        82                  NaN              82.0   
561  562                        76                  NaN              76.0   

     Rotten Tomatoes critics  Metacritic critics  Average critics  \
0                       73.0                 NaN              NaN   
1                       40.0                 NaN             40.0   
54                      54.0                48.0             51.0   
74                       NaN                 NaN              NaN   
103                     75.0                63.0             69.0   
109                     86.0                 NaN              NaN   
185                      NaN                 NaN              NaN   
284                     22.0                 NaN              NaN   
315                     29.0                72.0             51.0   
317                     40.0                 NaN             40.0   
413                      NaN                 NaN              NaN   
415                      0.0                 NaN              0.0   
442                     33.0                 NaN              NaN   
443                     17.0                 NaN             17.0   
477                     17.0                29.0             23.0   
558                     67.0                53.0             60.0   
561                     72.0                62.0             67.0   

     Rotten Tomatoes vs Metacritic deviance  Audience vs Critics deviance  
0                                       NaN                           NaN  
1                                       NaN                         -44.0  
54                                      NaN                           NaN  
74                                      NaN                           NaN  
103                                     NaN                           NaN  
109                                     NaN                           NaN  
185                                     NaN                           NaN  
284                                     NaN                           NaN  
315                                     NaN                         -31.0  
317                                     NaN                         -53.0  
413                                     NaN                           NaN  
415                                     NaN                         -36.0  
442                                     NaN                           NaN  
443                                     NaN                         -33.0  
477                                     NaN                           NaN  
558                                     NaN                         -22.0  
561                                     NaN                          -9.0

In [ ]:
df2.loc[df2['ID'] == 316, 'Metacritic Audience'] = 2 * (np.abs(df2.loc[df2['ID'] == 316, 'Audience vs Critics deviance']) + df2.loc[df2['ID'] == 316, 'Average critics']) - df2.loc[df2['ID'] == 316, 'Rotten Tomatoes Audience']

and we can fix the average audience like so:

In [ ]:
df2.loc[df2['ID'] == 316, 'Average audience'] = (df2.loc[df2['ID'] == 316, 'Metacritic Audience'] + df2.loc[df2['ID'] == 316, 'Rotten Tomatoes Audience']) / 2

Wr can also calculate the Rotten Tomatoes vs Metacritic deviance

In [ ]:
df2.loc[df2['ID'] == 316, 'Rotten Tomatoes vs Metacritic deviance'] = df2.loc[df2['ID'] == 316, 'Metacritic critics'] - df2.loc[df2['ID'] == 316, 'Rotten Tomatoes critics']

In [ ]:
ma = df2[df2['Metacritic Audience'].isna()][audience_cols]
ma

ID  Rotten Tomatoes Audience  Metacritic Audience  Average audience  \
0      1                        80                  NaN               NaN   
1      2                        84                  NaN              84.0   
54    55                        71                  NaN               NaN   
74    75                        89                  NaN              89.0   
103  104                        39                  NaN               NaN   
109  110                        70                  NaN               NaN   
185  186                       100                  NaN             100.0   
284  285                        29                  NaN               NaN   
317  318                        93                  NaN              93.0   
413  414                        79                  NaN               NaN   
415  416                        36                  NaN              36.0   
442  443                        58                  NaN               NaN   
443  444                        50                  NaN              50.0   
477  478                        87                  NaN               NaN   
558  559                        82                  NaN              82.0   
561  562                        76                  NaN              76.0   

     Rotten Tomatoes critics  Metacritic critics  Average critics  \
0                       73.0                 NaN              NaN   
1                       40.0                 NaN             40.0   
54                      54.0                48.0             51.0   
74                       NaN                 NaN              NaN   
103                     75.0                63.0             69.0   
109                     86.0                 NaN              NaN   
185                      NaN                 NaN              NaN   
284                     22.0                 NaN              NaN   
317                     40.0                 NaN             40.0   
413                      NaN                 NaN              NaN   
415                      0.0                 NaN              0.0   
442                     33.0                 NaN              NaN   
443                     17.0                 NaN             17.0   
477                     17.0                29.0             23.0   
558                     67.0                53.0             60.0   
561                     72.0                62.0             67.0   

     Rotten Tomatoes vs Metacritic deviance  Audience vs Critics deviance  
0                                       NaN                           NaN  
1                                       NaN                         -44.0  
54                                      NaN                           NaN  
74                                      NaN                           NaN  
103                                     NaN                           NaN  
109                                     NaN                           NaN  
185                                     NaN                           NaN  
284                                     NaN                           NaN  
317                                     NaN                         -53.0  
413                                     NaN                           NaN  
415                                     NaN                         -36.0  
442                                     NaN                           NaN  
443                                     NaN                         -33.0  
477                                     NaN                           NaN  
558                                     NaN                         -22.0  
561                                     NaN                          -9.0

In [ ]:
ma['Metacritic Audience'] = ma['Average audience']

In [ ]:
ma['Metacritic Audience'].fillna(value = df2['Metacritic Audience'].mean(), inplace = True)

In [ ]:
ma['Average audience'] = (ma['Rotten Tomatoes Audience'] + ma['Metacritic Audience']) / 2

In [ ]:
ma['Rotten Tomatoes critics'].fillna(value = df2['Rotten Tomatoes critics'].mean(), inplace = True)

In [ ]:
ma['Metacritic critics'].fillna(value = df2['Metacritic critics'].mean(), inplace = True)

for i, row in ma.iterrows():
  if pd.isna(ma.at[i, 'Average critics']):
    ma.at[i, 'Average critics'] = (ma.at[i, 'Rotten Tomatoes critics'] + ma.at[i, 'Metacritic critics']) / 2


In [ ]:
ma['Metacritic Audience'] = ma['Metacritic Audience'].astype('int')

In [ ]:
ma['Rotten Tomatoes vs Metacritic deviance'] = np.abs(ma['Rotten Tomatoes Audience'] - ma['Metacritic Audience'])
ma['Audience vs Critics deviance'] = np.abs(ma['Average audience'] - ma['Average critics'])
ma

ID  Rotten Tomatoes Audience  Metacritic Audience  Average audience  \
0      1                        80                   60              70.3   
1      2                        84                   84              84.0   
54    55                        71                   60              65.8   
74    75                        89                   89              89.0   
103  104                        39                   60              49.8   
109  110                        70                   60              65.3   
185  186                       100                  100             100.0   
284  285                        29                   60              44.8   
317  318                        93                   93              93.0   
413  414                        79                   60              69.8   
415  416                        36                   36              36.0   
442  443                        58                   60              59.3   
443  444                        50                   50              50.0   
477  478                        87                   60              73.8   
558  559                        82                   82              82.0   
561  562                        76                   76              76.0   

     Rotten Tomatoes critics  Metacritic critics  Average critics  \
0                       73.0                57.1             65.1   
1                       40.0                57.1             40.0   
54                      54.0                48.0             51.0   
74                      62.1                57.1             59.6   
103                     75.0                63.0             69.0   
109                     86.0                57.1             71.6   
185                     62.1                57.1             59.6   
284                     22.0                57.1             39.6   
317                     40.0                57.1             40.0   
413                     62.1                57.1             59.6   
415                      0.0                57.1              0.0   
442                     33.0                57.1             45.1   
443                     17.0                57.1             17.0   
477                     17.0                29.0             23.0   
558                     67.0                53.0             60.0   
561                     72.0                62.0             67.0   

     Rotten Tomatoes vs Metacritic deviance  Audience vs Critics deviance  
0                                        20                           5.3  
1                                         0                          44.0  
54                                       11                          14.8  
74                                        0                          29.4  
103                                      21                          19.2  
109                                      10                           6.2  
185                                       0                          40.4  
284                                      31                           5.3  
317                                       0                          53.0  
413                                      19                          10.3  
415                                       0                          36.0  
442                                       2                          14.3  
443                                       0                          33.0  
477                                      27                          50.8  
558                                       0                          22.0  
561                                       0                           9.0

In [ ]:
for i, row in ma.iterrows():
  id = row['ID']
  df2.loc[df2['ID'] == id, 'Metacritic Audience'] = ma.loc[ma['ID'] == id, 'Metacritic Audience']
  df2.loc[df2['ID'] == id, 'Average audience'] = ma.loc[ma['ID'] == id, 'Average audience']
  df2.loc[df2['ID'] == id, 'Rotten Tomatoes critics'] = ma.loc[ma['ID'] == id, 'Rotten Tomatoes critics']
  df2.loc[df2['ID'] == id, 'Metacritic critics'] = ma.loc[ma['ID'] == id, 'Metacritic critics']
  df2.loc[df2['ID'] == id, 'Average critics'] = ma.loc[ma['ID'] == id, 'Average critics']
  df2.loc[df2['ID'] == id, 'Rotten Tomatoes vs Metacritic deviance'] = ma.loc[ma['ID'] == id, 'Rotten Tomatoes vs Metacritic deviance']
  df2.loc[df2['ID'] == id, 'Audience vs Critics deviance'] = ma.loc[ma['ID'] == id, 'Audience vs Critics deviance']

In [ ]:
df2[df2['Average audience'].isna()][['ID']]
df2.loc[df2['ID'] == 357, 'Average audience'] = (df2.loc[df2['ID'] == 357, 'Rotten Tomatoes Audience'] + df2.loc[df2['ID'] == 357, 'Metacritic Audience']) / 2

In [ ]:
ac = df2[df2['Audience vs Critics deviance'].isna()][['ID', 'Average critics', 'Average audience', 'Rotten Tomatoes critics', 'Metacritic critics', 'Audience vs Critics deviance']]
ac

ID  Average critics  Average audience  Rotten Tomatoes critics  \
216  217              NaN              85.0                     58.0   
447  448              NaN              37.0                      NaN   

     Metacritic critics  Audience vs Critics deviance  
216                 NaN                           NaN  
447                79.0                           NaN

In [ ]:
ac['Rotten Tomatoes critics'].fillna(value = df2['Rotten Tomatoes critics'].mean(), inplace = True)
ac['Metacritic critics'].fillna(value = df2['Metacritic critics'].mean(), inplace = True)
ac['Rotten Tomatoes critics'] = ac['Rotten Tomatoes critics'].astype('int')
ac['Metacritic critics'] = ac['Metacritic critics'].astype('int')
ac

ID  Average critics  Average audience  Rotten Tomatoes critics  \
216  217              NaN              85.0                       58   
447  448              NaN              37.0                       62   

     Metacritic critics  Audience vs Critics deviance  
216                  57                           NaN  
447                  79                           NaN

In [ ]:
ac['Average critics'] = (ac['Rotten Tomatoes critics'] + ac['Metacritic critics']) / 2
ac['Audience vs Critics deviance'] = np.abs(ac['Average critics'] - ac['Average audience'])
ac

ID  Average critics  Average audience  Rotten Tomatoes critics  \
216  217             57.5              85.0                       58   
447  448             70.5              37.0                       62   

     Metacritic critics  Audience vs Critics deviance  
216                  57                          27.5  
447                  79                          33.5

In [ ]:
for i, row in ac.iterrows():
  id = row['ID']
  df2.loc[df2['ID'] == id, 'Metacritic critics'] = ac.loc[ac['ID'] == id, 'Metacritic critics']
  df2.loc[df2['ID'] == id, 'Average audience'] = ac.loc[ac['ID'] == id, 'Average audience']
  df2.loc[df2['ID'] == id, 'Rotten Tomatoes critics'] = ac.loc[ac['ID'] == id, 'Rotten Tomatoes critics']
  df2.loc[df2['ID'] == id, 'Metacritic critics'] = ac.loc[ac['ID'] == id, 'Metacritic critics']
  df2.loc[df2['ID'] == id, 'Audience vs Critics deviance'] = ac.loc[ac['ID'] == id, 'Audience vs Critics deviance']

In [ ]:
df2['Rotten Tomatoes critics'] = df2['Rotten Tomatoes critics'].astype('int')

ac = df2[df2['Average critics'].isna()][['ID', 'Average critics', 'Rotten Tomatoes critics', 'Metacritic critics']]
ac['Metacritic critics'] = ac['Metacritic critics'].astype('int')
ac

ID  Average critics  Rotten Tomatoes critics  Metacritic critics
216  217              NaN                       58                  57
447  448              NaN                       62                  79

In [ ]:
ac['Average critics'] = (ac['Rotten Tomatoes critics'] + ac['Metacritic critics']) / 2
ac

ID  Average critics  Rotten Tomatoes critics  Metacritic critics
216  217             57.5                       58                  57
447  448             70.5                       62                  79

In [ ]:
for i, row in ac.iterrows():
  id = row['ID']
  df2.loc[df2['ID'] == id, 'Average critics'] = ac.loc[ac['ID'] == id, 'Average critics']

In [ ]:
df2['Metacritic critics'].fillna(value = df2['Metacritic critics'].mean(), inplace = True)
df2['Metacritic critics'] = df2['Metacritic critics'].astype('int')

In [ ]:
df2['Budget recovered'].fillna(value = df2['Budget recovered'].mean(), inplace = True)
df2['Budget ($million)'].fillna(value = df2['Budget ($million)'].mean(), inplace = True)
df2['Budget recovered opening weekend'].fillna(value = df2['Budget recovered opening weekend'].mean(), inplace = True)


In [ ]:
(df2.isna()).sum()

ID                                          0
Year                                        0
Rotten Tomatoes critics                     0
Metacritic critics                          0
Average critics                             0
Rotten Tomatoes Audience                    0
Metacritic Audience                         0
Rotten Tomatoes vs Metacritic deviance      0
Average audience                            0
Audience vs Critics deviance                0
Primary Genre                             306
Genre                                       0
Opening Weekend                             0
Opening weekend ($million)                  0
Domestic Gross                              0
Domestic gross ($million)                   0
Foreign Gross ($million)                    0
Foreign Gross                               0
Worldwide Gross                             0
Worldwide Gross ($million)                  0
of Gross earned abroad                      0
Budget ($million)                 

We will drop the Primary Genre column and we have eliminated all the missing values.

In [ ]:
df2 = df2.drop(columns = ['Primary Genre'])

Let's continue, we have to make the data so that it is like the data that our model was trained with.

We drop the same columns

In [ ]:
df2 = df2.drop(columns = ['Foreign Gross', 'Worldwide Gross', 'Budget recovered opening weekend', 'Domestic Gross', 'Opening Weekend', 'Rotten Tomatoes critics'])

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 17 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   ID                                      565 non-null    int64  
 1   Year                                    565 non-null    int64  
 2   Metacritic critics                      565 non-null    int64  
 3   Average critics                         565 non-null    float64
 4   Rotten Tomatoes Audience                565 non-null    int64  
 5   Metacritic Audience                     565 non-null    float64
 6   Rotten Tomatoes vs Metacritic deviance  565 non-null    float64
 7   Average audience                        565 non-null    float64
 8   Audience vs Critics deviance            565 non-null    float64
 9   Genre                                   565 non-null    object 
 10  Opening weekend ($million)              565 non-null    float6

The thing that is left is to fix the Genre column.

All the values must have these genres, any other genre will not be acceptable due to the fact that our model has not seen any movies with this genres.

In [ ]:
list(genre_set)

['action',
 'romance',
 'adventure',
 'animation',
 'western',
 'mystery',
 'comedy',
 'biography',
 'sports',
 'family',
 'thriller',
 'documentary',
 'sci-fi',
 'crime',
 'period',
 'musical',
 'history',
 'fantasy',
 'horror',
 'drama',
 'war']

In [ ]:
genre_df2 = pd.DataFrame(data = 0, index = np.arange(len(df2)), columns = list(genre_set))
genre_df2

action  romance  adventure  animation  western  mystery  comedy  \
0         0        0          0          0        0        0       0   
1         0        0          0          0        0        0       0   
2         0        0          0          0        0        0       0   
3         0        0          0          0        0        0       0   
4         0        0          0          0        0        0       0   
..      ...      ...        ...        ...      ...      ...     ...   
560       0        0          0          0        0        0       0   
561       0        0          0          0        0        0       0   
562       0        0          0          0        0        0       0   
563       0        0          0          0        0        0       0   
564       0        0          0          0        0        0       0   

     biography  sports  family  ...  documentary  sci-fi  crime  period  \
0            0       0       0  ...            0       0      0       0   
1            0       0       0  ...            0       0      0       0   
2            0       0       0  ...            0       0      0       0   
3            0       0       0  ...            0       0      0       0   
4            0       0       0  ...            0       0      0       0   
..         ...     ...     ...  ...          ...     ...    ...     ...   
560          0       0       0  ...            0       0      0       0   
561          0       0       0  ...            0       0      0       0   
562          0       0       0  ...            0       0      0       0   
563          0       0       0  ...            0       0      0       0   
564          0       0       0  ...            0       0      0       0   

     musical  history  fantasy  horror  drama  war  
0          0        0        0       0      0    0  
1          0        0        0       0      0    0  
2          0        0        0       0      0    0  
3          0        0        0       0      0    0  
4          0        0        0       0      0    0  
..       ...      ...      ...     ...    ...  ...  
560        0        0        0       0      0    0  
561        0        0        0       0      0    0  
562        0        0        0       0      0    0  
563        0        0        0       0      0    0  
564        0        0        0       0      0    0  

[565 rows x 21 columns]

In [ ]:
genre_set2 = set()

In [ ]:
def change_genre2(df_row):
  genres = df_row['Genre'].lower().replace(" ", "").replace(".", ",").split(',')
  for genre in genres:
    if genre == "":
      continue
    genre_set2.add(genre)

In [ ]:
df2.apply(change_genre2, axis = 1)

0      None
1      None
2      None
3      None
4      None
       ... 
560    None
561    None
562    None
563    None
564    None
Length: 565, dtype: object

In [ ]:
genre_set2

{'action',
 'adventure',
 'animation',
 'biography',
 'blackcomedy',
 'comedy',
 'crime',
 'drama',
 'family',
 'fanstasy',
 'fantasy',
 'history',
 'holiday',
 'horror',
 'horror/mystery',
 'music',
 'musical',
 'mystery',
 'mystery&thriller',
 'romance',
 'sci-fi',
 'sport',
 'suspense',
 'thriler',
 'thriller',
 'war',
 'western'}

---

In [ ]:
df2.index = range(len(df2))

In [ ]:
for i, data in df2.iterrows():
  genres = df2.loc[i, 'Genre'].lower().replace(" ", "").replace(".", ",").split(',')

  for genre in genres:
    if genre == "":
      continue
    elif genre == "horror/mystery":
      genre_df2.loc[i, "horror"] = 1
      genre_df2.loc[i, "mystery"] = 1
    elif genre == "music":
      genre_df2.loc[i, "musical"] = 1
    elif genre == "sport":
      genre_df2.loc[i, "sports"] = 1
    elif genre == "thriler":
      genre_df2.loc[i, "thriller"] = 1
    elif genre == "blackcomedy":
      genre_df2.loc[i, "comedy"] = 1
    elif genre == 'mystery&thriller':
      genre_df2.loc[i, 'mystery'] = 1
      genre_df2.loc[i, 'thriller'] = 1
    elif genre == 'fanstasy':
      genre_df2.loc[i, 'fantasy'] = 1
    elif genre == 'holiday' or genre == 'suspense':
      continue
    else:
      genre_df2.loc[i, genre] = 1

In [ ]:
genre_df2

action  romance  adventure  animation  western  mystery  comedy  \
0         1        0          0          0        0        0       0   
1         0        0          0          0        0        0       0   
2         0        0          0          0        0        0       1   
3         0        1          0          0        0        0       0   
4         0        1          0          0        0        0       1   
..      ...      ...        ...        ...      ...      ...     ...   
560       0        0          0          0        0        0       0   
561       0        0          0          0        0        0       1   
562       1        0          0          0        0        0       0   
563       0        0          0          1        0        0       1   
564       0        0          0          0        0        1       0   

     biography  sports  family  ...  documentary  sci-fi  crime  period  \
0            0       0       0  ...            0       0      0       0   
1            0       0       1  ...            0       0      0       0   
2            0       0       0  ...            0       0      0       0   
3            0       0       0  ...            0       0      0       0   
4            0       0       0  ...            0       0      0       0   
..         ...     ...     ...  ...          ...     ...    ...     ...   
560          0       0       0  ...            0       0      0       0   
561          0       0       0  ...            0       0      0       0   
562          0       0       0  ...            0       0      0       0   
563          0       0       1  ...            0       0      0       0   
564          0       0       0  ...            0       1      1       0   

     musical  history  fantasy  horror  drama  war  
0          0        0        0       0      0    0  
1          0        0        0       0      0    0  
2          0        0        0       0      0    0  
3          0        0        1       0      0    0  
4          0        0        0       0      0    0  
..       ...      ...      ...     ...    ...  ...  
560        0        0        0       0      1    0  
561        0        0        0       0      0    0  
562        0        0        0       0      0    0  
563        0        0        0       0      0    0  
564        0        0        0       0      1    0  

[565 rows x 21 columns]

In [ ]:
genre_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 565 entries, 0 to 564
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   action       565 non-null    int64
 1   romance      565 non-null    int64
 2   adventure    565 non-null    int64
 3   animation    565 non-null    int64
 4   western      565 non-null    int64
 5   mystery      565 non-null    int64
 6   comedy       565 non-null    int64
 7   biography    565 non-null    int64
 8   sports       565 non-null    int64
 9   family       565 non-null    int64
 10  thriller     565 non-null    int64
 11  documentary  565 non-null    int64
 12  sci-fi       565 non-null    int64
 13  crime        565 non-null    int64
 14  period       565 non-null    int64
 15  musical      565 non-null    int64
 16  history      565 non-null    int64
 17  fantasy      565 non-null    int64
 18  horror       565 non-null    int64
 19  drama        565 non-null    int64
 20  war       

In [ ]:
df2 = df2.drop(columns = ['Genre'])

In [ ]:
id_df = df2['ID']
df2 = df2.drop(columns = ['ID'])

In [ ]:
# Normalize the values
df2 = (df2 - df2.mean()) / df2.std()

In [ ]:
df2

Year  Metacritic critics  Average critics  Rotten Tomatoes Audience  \
0    -0.5                -0.0              0.3                       0.4   
1     1.6                -0.0             -1.0                       0.6   
2    -0.5                -1.1             -1.2                       1.1   
3     1.6                 0.2              0.3                       0.0   
4    -1.2                -1.0              0.2                      -0.1   
..    ...                 ...              ...                       ...   
560  -1.2                 2.1              1.7                       0.7   
561   0.9                 0.3              0.4                       0.2   
562   0.2                -0.1              0.1                      -0.1   
563   0.9                -0.5              0.3                       1.3   
564  -0.5                -2.4             -2.2                      -1.9   

     Metacritic Audience  Rotten Tomatoes vs Metacritic deviance  \
0                   -0.1                                     0.5   
1                    1.6                                    -0.7   
2                    0.4                                     1.0   
3                    0.4                                    -0.3   
4                   -1.2                                     0.8   
..                   ...                                     ...   
560                  1.6                                    -0.6   
561                  1.1                                    -0.7   
562                  0.2                                    -0.3   
563                  0.3                                     1.2   
564                 -1.3                                    -1.0   

     Average audience  Audience vs Critics deviance  \
0                 0.2                           0.6   
1                 1.2                           2.8   
2                 0.9                          -2.1   
3                 0.2                           0.1   
4                -0.7                           0.7   
..                ...                           ...   
560               1.2                           0.8   
561               0.6                           0.8   
562               0.0                          -0.0   
563               1.0                          -0.6   
564              -1.8                          -1.1   

     Opening weekend ($million)  Domestic gross ($million)  \
0                           0.0                       -0.5   
1                          -0.5                       -0.5   
2                          -0.3                       -0.4   
3                          -0.5                       -0.5   
4                          -0.1                       -0.1   
..                          ...                        ...   
560                        -0.6                       -0.4   
561                        -0.5                       -0.5   
562                         0.0                       -0.0   
563                        -0.2                       -0.2   
564                        -0.5                       -0.5   

     Foreign Gross ($million)  Worldwide Gross ($million)  \
0                        -0.1                        -0.3   
1                         0.3                        -0.0   
2                        -0.5                        -0.5   
3                        -0.4                        -0.5   
4                        -0.3                        -0.2   
..                        ...                         ...   
560                      -0.5                        -0.5   
561                      -0.5                        -0.5   
562                       0.0                        -0.0   
563                       0.1                         0.0   
564                      -0.5                        -0.5   

     of Gross earned abroad  Budget ($million)  Budget recovered  
0                       2.0               -0.6              -0.0  
1 

In [ ]:
genre_df2 = genre_df2.astype('float')
genre_df2

action  romance  adventure  animation  western  mystery  comedy  \
0       1.0      0.0        0.0        0.0      0.0      0.0     0.0   
1       0.0      0.0        0.0        0.0      0.0      0.0     0.0   
2       0.0      0.0        0.0        0.0      0.0      0.0     1.0   
3       0.0      1.0        0.0        0.0      0.0      0.0     0.0   
4       0.0      1.0        0.0        0.0      0.0      0.0     1.0   
..      ...      ...        ...        ...      ...      ...     ...   
560     0.0      0.0        0.0        0.0      0.0      0.0     0.0   
561     0.0      0.0        0.0        0.0      0.0      0.0     1.0   
562     1.0      0.0        0.0        0.0      0.0      0.0     0.0   
563     0.0      0.0        0.0        1.0      0.0      0.0     1.0   
564     0.0      0.0        0.0        0.0      0.0      1.0     0.0   

     biography  sports  family  ...  documentary  sci-fi  crime  period  \
0          0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
1          0.0     0.0     1.0  ...          0.0     0.0    0.0     0.0   
2          0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
3          0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
4          0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
..         ...     ...     ...  ...          ...     ...    ...     ...   
560        0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
561        0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
562        0.0     0.0     0.0  ...          0.0     0.0    0.0     0.0   
563        0.0     0.0     1.0  ...          0.0     0.0    0.0     0.0   
564        0.0     0.0     0.0  ...          0.0     1.0    1.0     0.0   

     musical  history  fantasy  horror  drama  war  
0        0.0      0.0      0.0     0.0    0.0  0.0  
1        0.0      0.0      0.0     0.0    0.0  0.0  
2        0.0      0.0      0.0     0.0    0.0  0.0  
3        0.0      0.0      1.0     0.0    0.0  0.0  
4        0.0      0.0      0.0     0.0    0.0  0.0  
..       ...      ...      ...     ...    ...  ...  
560      0.0      0.0      0.0     0.0    1.0  0.0  
561      0.0      0.0      0.0     0.0    0.0  0.0  
562      0.0      0.0      0.0     0.0    0.0  0.0  
563      0.0      0.0      0.0     0.0    0.0  0.0  
564      0.0      0.0      0.0     0.0    1.0  0.0  

[565 rows x 21 columns]

In [ ]:
Xtest = pd.concat([df2, genre_df2], axis = 1)
Xtest

Year  Metacritic critics  Average critics  Rotten Tomatoes Audience  \
0    -0.5                -0.0              0.3                       0.4   
1     1.6                -0.0             -1.0                       0.6   
2    -0.5                -1.1             -1.2                       1.1   
3     1.6                 0.2              0.3                       0.0   
4    -1.2                -1.0              0.2                      -0.1   
..    ...                 ...              ...                       ...   
560  -1.2                 2.1              1.7                       0.7   
561   0.9                 0.3              0.4                       0.2   
562   0.2                -0.1              0.1                      -0.1   
563   0.9                -0.5              0.3                       1.3   
564  -0.5                -2.4             -2.2                      -1.9   

     Metacritic Audience  Rotten Tomatoes vs Metacritic deviance  \
0                   -0.1                                     0.5   
1                    1.6                                    -0.7   
2                    0.4                                     1.0   
3                    0.4                                    -0.3   
4                   -1.2                                     0.8   
..                   ...                                     ...   
560                  1.6                                    -0.6   
561                  1.1                                    -0.7   
562                  0.2                                    -0.3   
563                  0.3                                     1.2   
564                 -1.3                                    -1.0   

     Average audience  Audience vs Critics deviance  \
0                 0.2                           0.6   
1                 1.2                           2.8   
2                 0.9                          -2.1   
3                 0.2                           0.1   
4                -0.7                           0.7   
..                ...                           ...   
560               1.2                           0.8   
561               0.6                           0.8   
562               0.0                          -0.0   
563               1.0                          -0.6   
564              -1.8                          -1.1   

     Opening weekend ($million)  Domestic gross ($million)  ...  documentary  \
0                           0.0                       -0.5  ...          0.0   
1                          -0.5                       -0.5  ...          0.0   
2                          -0.3                       -0.4  ...          0.0   
3                          -0.5                       -0.5  ...          0.0   
4                          -0.1                       -0.1  ...          0.0   
..                          ...                        ...  ...          ...   
560                        -0.6                       -0.4  ...          0.0   
561                        -0.5                       -0.5  ...          0.0   
562                         0.0                       -0.0  ...          0.0   
563                        -0.2                       -0.2  ...          0.0   
564                        -0.5                       -0.5  ...          0.0   

     sci-fi  crime  period  musical  history  fantasy  horror  drama  war  
0       0.0    0.0     0.0      0.0      0.0      0.0     0.0    0.0  0.0  
1       0.0    0.0     0.0      0.0      0.0      0.0     0.0    0.0  0.0  
2       0.0    0.0     0.0      0.0      0.0      0.0     0.0    0.0  0.0  
3       0.0    0.0     0.0      0.0      0.0      1.0     0.0    0.0  0.0  
4       0.0    0.0     0.0      0.0      0.0      0.0     0.0    0.0  0.0  
..      ...    ...     ...      ...      ...      ...     ...    ...  ...  
560     0.0    0.0     0.0      0.0      0.0      0.0     0.0    1.0  0.0  
561     0.0    0.0     0.0      0.0      0.0 

In [ ]:
# Xtest.to_excel('/content/drive/MyDrive/DataMining/Assignment/test_data.xlsx', index=False)

In [ ]:
Xtest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 36 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Year                                    565 non-null    float64
 1   Metacritic critics                      565 non-null    float64
 2   Average critics                         565 non-null    float64
 3   Rotten Tomatoes Audience                565 non-null    float64
 4   Metacritic Audience                     565 non-null    float64
 5   Rotten Tomatoes vs Metacritic deviance  565 non-null    float64
 6   Average audience                        565 non-null    float64
 7   Audience vs Critics deviance            565 non-null    float64
 8   Opening weekend ($million)              565 non-null    float64
 9   Domestic gross ($million)               565 non-null    float64
 10  Foreign Gross ($million)                565 non-null    float6

In [ ]:
final_preds = dtree.predict(Xtest)


In [ ]:
preds_df = pd.DataFrame({'ID': id_df, 'OSCAR': final_preds})
preds_df

ID  OSCAR
0      1      1
1      2      0
2      3      0
3      4      0
4      5      0
..   ...    ...
560  561      0
561  562      0
562  563      0
563  564      0
564  565      0

[565 rows x 2 columns]

In [ ]:
(preds_df == 1).sum()

ID        1
OSCAR    27
dtype: int64

In [ ]:
# save the dataframe to a CSV file
# preds_df.to_csv('/content/drive/MyDrive/DataMining/Assignment/predictions.csv', index=False)

---
## Custering

#### K-means

Let's use some clustering algorithms.

In [ ]:
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.cluster import AgglomerativeClustering
from sklearn import metrics

In [ ]:
X

Year  Metacritic critics  Average critics  Rotten Tomatoes Audience  \
0     -1.6                -0.2              0.1                       1.5   
1     -1.6                 1.3              1.3                       1.4   
2     -1.6                -0.0             -0.1                      -0.3   
3     -1.6                 0.1              0.1                       1.1   
4     -1.6                -1.4             -1.4                      -1.8   
...    ...                 ...              ...                       ...   
1381   1.5                 1.1              1.2                       1.7   
1382   1.5                -1.2             -1.3                      -1.7   
1383   1.5                 0.7              1.0                       1.7   
1384   1.5                 1.3              1.4                       1.5   
1385   1.5                -0.7             -0.4                      -1.4   

      Metacritic Audience  Rotten Tomatoes vs Metacritic deviance  \
0                     0.6                                     1.1   
1                     0.8                                     0.5   
2                     0.2                                    -0.0   
3                     0.8                                    -0.0   
4                    -1.3                                     0.6   
...                   ...                                     ...   
1381                  1.1                                     0.6   
1382                 -1.7                                    -0.2   
1383                  1.1                                     0.6   
1384                  1.1                                     0.2   
1385                 -1.1                                     0.1   

      Average audience  Audience vs Critics deviance  \
0                  1.2                           1.1   
1                  1.2                          -1.1   
2                 -0.1                          -0.4   
3                  1.1                           1.0   
4                 -1.7                           0.3   
...                ...                           ...   
1381               1.5                          -0.9   
1382              -1.8                          -0.2   
1383               1.5                          -0.5   
1384               1.5                          -1.3   
1385              -1.4                          -1.2   

      Opening weekend ($million)  Domestic gross ($million)  ...  documentary  \
0                            1.7                        1.6  ...          0.0   
1                           -0.3                       -0.2  ...          0.0   
2                           -0.3                       -0.4  ...          0.0   
3                           -0.7                       -0.6  ...          0.0   
4                           -0.5                       -0.4  ...          0.0   
...                          ...                        ...  ...          ...   
1381                        -0.8                       -0.5  ...          0.0   
1382                        -0.6                       -0.7  ...          0.0   
1383                         0.1                        0.3  ...          0.0   
1384                         2.8                        3.9  ...          0.0   
1385                        -0.1                       -0.3  ...          0.0   

      sci-fi  crime  period  musical  history  fantasy  horror  drama  war  
0        0.0    0.0     1.0      0.0      0.0      0.0     0.0    0.0  0.0  
1        0.0    0.0     0.0      0.0      0.0      0.0     0.0    0.0  0.0  
2        0.0    0.0     0.0      0.0      0.0      0.0     1.0    0.0  0.0  
3        0.0    0.0     0.0      1.0      0.0      0.0     0.0    0.0  0.0  
4        1.0    0.0     0.0      0.0      0.0      0.0     1.0    0.0  0.0  
...      ...    ...     ...      ...      ...      ...     ...    ...  ...  
1381     0.0    0.0     0.0      0.0      0.0      0.0     0.0    1

In [ ]:
kclu_k = KMeans(n_clusters=2)

In [ ]:
kclu_k.fit(X)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=2)

In [ ]:
kclu_k.labels_

array([0, 0, 1, ..., 0, 0, 1], dtype=int32)

In [ ]:
dfcluster = pd.DataFrame(kclu_k.labels_,columns=['cluster'])
dfall = pd.concat([X, dfcluster], axis = 1)
dfall.head()

Year  Metacritic critics  Average critics  Rotten Tomatoes Audience  \
0  -1.6                -0.2              0.1                       1.5   
1  -1.6                 1.3              1.3                       1.4   
2  -1.6                -0.0             -0.1                      -0.3   
3  -1.6                 0.1              0.1                       1.1   
4  -1.6                -1.4             -1.4                      -1.8   

   Metacritic Audience  Rotten Tomatoes vs Metacritic deviance  \
0                  0.6                                     1.1   
1                  0.8                                     0.5   
2                  0.2                                    -0.0   
3                  0.8                                    -0.0   
4                 -1.3                                     0.6   

   Average audience  Audience vs Critics deviance  Opening weekend ($million)  \
0               1.2                           1.1                         1.7   
1               1.2                          -1.1                        -0.3   
2              -0.1                          -0.4                        -0.3   
3               1.1                           1.0                        -0.7   
4              -1.7                           0.3                        -0.5   

   Domestic gross ($million)  ...  sci-fi  crime  period  musical  history  \
0                        1.6  ...     0.0    0.0     1.0      0.0      0.0   
1                       -0.2  ...     0.0    0.0     0.0      0.0      0.0   
2                       -0.4  ...     0.0    0.0     0.0      0.0      0.0   
3                       -0.6  ...     0.0    0.0     0.0      1.0      0.0   
4                       -0.4  ...     1.0    0.0     0.0      0.0      0.0   

   fantasy  horror  drama  war  cluster  
0      0.0     0.0    0.0  0.0        0  
1      0.0     0.0    0.0  0.0        0  
2      0.0     1.0    0.0  0.0        1  
3      0.0     0.0    0.0  0.0        0  
4      0.0     1.0    0.0  0.0        1  

[5 rows x 37 columns]

In [ ]:
metrics.silhouette_score(X, dfall['cluster'], metric='euclidean')

0.2081491706376364

In [ ]:
dfall = pd.concat([dfall, y], axis = 1)
dfall

Year  Metacritic critics  Average critics  Rotten Tomatoes Audience  \
0     -1.6                -0.2              0.1                       1.5   
1     -1.6                 1.3              1.3                       1.4   
2     -1.6                -0.0             -0.1                      -0.3   
3     -1.6                 0.1              0.1                       1.1   
4     -1.6                -1.4             -1.4                      -1.8   
...    ...                 ...              ...                       ...   
1381   1.5                 1.1              1.2                       1.7   
1382   1.5                -1.2             -1.3                      -1.7   
1383   1.5                 0.7              1.0                       1.7   
1384   1.5                 1.3              1.4                       1.5   
1385   1.5                -0.7             -0.4                      -1.4   

      Metacritic Audience  Rotten Tomatoes vs Metacritic deviance  \
0                     0.6                                     1.1   
1                     0.8                                     0.5   
2                     0.2                                    -0.0   
3                     0.8                                    -0.0   
4                    -1.3                                     0.6   
...                   ...                                     ...   
1381                  1.1                                     0.6   
1382                 -1.7                                    -0.2   
1383                  1.1                                     0.6   
1384                  1.1                                     0.2   
1385                 -1.1                                     0.1   

      Average audience  Audience vs Critics deviance  \
0                  1.2                           1.1   
1                  1.2                          -1.1   
2                 -0.1                          -0.4   
3                  1.1                           1.0   
4                 -1.7                           0.3   
...                ...                           ...   
1381               1.5                          -0.9   
1382              -1.8                          -0.2   
1383               1.5                          -0.5   
1384               1.5                          -1.3   
1385              -1.4                          -1.2   

      Opening weekend ($million)  Domestic gross ($million)  ...  crime  \
0                            1.7                        1.6  ...    0.0   
1                           -0.3                       -0.2  ...    0.0   
2                           -0.3                       -0.4  ...    0.0   
3                           -0.7                       -0.6  ...    0.0   
4                           -0.5                       -0.4  ...    0.0   
...                          ...                        ...  ...    ...   
1381                        -0.8                       -0.5  ...    0.0   
1382                        -0.6                       -0.7  ...    0.0   
1383                         0.1                        0.3  ...    0.0   
1384                         2.8                        3.9  ...    0.0   
1385                        -0.1                       -0.3  ...    0.0   

      period  musical  history  fantasy  horror  drama  war  cluster  \
0        1.0      0.0      0.0      0.0     0.0    0.0  0.0        0   
1        0.0      0.0      0.0      0.0     0.0    0.0  0.0        0   
2        0.0      0.0      0.0      0.0     1.0    0.0  0.0        1   
3        0.0      1.0      0.0      0.0     0.0    0.0  0.0        0   
4        0.0      0.0      0.0      0.0     1.0    0.0  0.0        1   
...      ...      ...      ...      ...     ...    ...  ...      ...   
1381     0.0      0.0      0.0      0.0     0.0    1.0  0.0        0   
1382     0.0      0.0      0.0      0.0     1.0    0.0  0.0        1   
1383     0.0      0.0      0.0

In [ ]:
clu_oscar = dfall[['cluster', 'Oscar Winners']]

In [ ]:
(clu_oscar == 1).sum()

cluster          702
Oscar Winners     56
dtype: int64

In [ ]:
(clu_oscar == 0).sum()

cluster           684
Oscar Winners    1330
dtype: int64

In [ ]:
counter = 0

for i, data in clu_oscar.iterrows():
  cluster = clu_oscar.at[i, 'cluster']
  oscar = clu_oscar.at[i, 'Oscar Winners']

  if cluster == 1 and oscar == 1:
    counter += 1

counter

3

#### DBSCAN

In [ ]:
kclu_aggl = AgglomerativeClustering(n_clusters=2, linkage='ward')

In [ ]:
kclu_aggl.fit(X)

AgglomerativeClustering()

In [ ]:
kclu_aggl.labels_

array([1, 0, 0, ..., 0, 1, 0])

In [ ]:
dfcluster_aggl = pd.DataFrame(kclu_aggl.labels_,columns=['cluster'])
dfall_aggl = pd.concat([X, dfcluster_aggl], axis = 1)
dfall_aggl.head()

Year  Metacritic critics  Average critics  Rotten Tomatoes Audience  \
0  -1.6                -0.2              0.1                       1.5   
1  -1.6                 1.3              1.3                       1.4   
2  -1.6                -0.0             -0.1                      -0.3   
3  -1.6                 0.1              0.1                       1.1   
4  -1.6                -1.4             -1.4                      -1.8   

   Metacritic Audience  Rotten Tomatoes vs Metacritic deviance  \
0                  0.6                                     1.1   
1                  0.8                                     0.5   
2                  0.2                                    -0.0   
3                  0.8                                    -0.0   
4                 -1.3                                     0.6   

   Average audience  Audience vs Critics deviance  Opening weekend ($million)  \
0               1.2                           1.1                         1.7   
1               1.2                          -1.1                        -0.3   
2              -0.1                          -0.4                        -0.3   
3               1.1                           1.0                        -0.7   
4              -1.7                           0.3                        -0.5   

   Domestic gross ($million)  ...  sci-fi  crime  period  musical  history  \
0                        1.6  ...     0.0    0.0     1.0      0.0      0.0   
1                       -0.2  ...     0.0    0.0     0.0      0.0      0.0   
2                       -0.4  ...     0.0    0.0     0.0      0.0      0.0   
3                       -0.6  ...     0.0    0.0     0.0      1.0      0.0   
4                       -0.4  ...     1.0    0.0     0.0      0.0      0.0   

   fantasy  horror  drama  war  cluster  
0      0.0     0.0    0.0  0.0        1  
1      0.0     0.0    0.0  0.0        0  
2      0.0     1.0    0.0  0.0        0  
3      0.0     0.0    0.0  0.0        0  
4      0.0     1.0    0.0  0.0        0  

[5 rows x 37 columns]

In [ ]:
dfall_aggl = pd.concat([dfall_aggl, y], axis = 1)
dfall_aggl

Year  Metacritic critics  Average critics  Rotten Tomatoes Audience  \
0     -1.6                -0.2              0.1                       1.5   
1     -1.6                 1.3              1.3                       1.4   
2     -1.6                -0.0             -0.1                      -0.3   
3     -1.6                 0.1              0.1                       1.1   
4     -1.6                -1.4             -1.4                      -1.8   
...    ...                 ...              ...                       ...   
1381   1.5                 1.1              1.2                       1.7   
1382   1.5                -1.2             -1.3                      -1.7   
1383   1.5                 0.7              1.0                       1.7   
1384   1.5                 1.3              1.4                       1.5   
1385   1.5                -0.7             -0.4                      -1.4   

      Metacritic Audience  Rotten Tomatoes vs Metacritic deviance  \
0                     0.6                                     1.1   
1                     0.8                                     0.5   
2                     0.2                                    -0.0   
3                     0.8                                    -0.0   
4                    -1.3                                     0.6   
...                   ...                                     ...   
1381                  1.1                                     0.6   
1382                 -1.7                                    -0.2   
1383                  1.1                                     0.6   
1384                  1.1                                     0.2   
1385                 -1.1                                     0.1   

      Average audience  Audience vs Critics deviance  \
0                  1.2                           1.1   
1                  1.2                          -1.1   
2                 -0.1                          -0.4   
3                  1.1                           1.0   
4                 -1.7                           0.3   
...                ...                           ...   
1381               1.5                          -0.9   
1382              -1.8                          -0.2   
1383               1.5                          -0.5   
1384               1.5                          -1.3   
1385              -1.4                          -1.2   

      Opening weekend ($million)  Domestic gross ($million)  ...  crime  \
0                            1.7                        1.6  ...    0.0   
1                           -0.3                       -0.2  ...    0.0   
2                           -0.3                       -0.4  ...    0.0   
3                           -0.7                       -0.6  ...    0.0   
4                           -0.5                       -0.4  ...    0.0   
...                          ...                        ...  ...    ...   
1381                        -0.8                       -0.5  ...    0.0   
1382                        -0.6                       -0.7  ...    0.0   
1383                         0.1                        0.3  ...    0.0   
1384                         2.8                        3.9  ...    0.0   
1385                        -0.1                       -0.3  ...    0.0   

      period  musical  history  fantasy  horror  drama  war  cluster  \
0        1.0      0.0      0.0      0.0     0.0    0.0  0.0        1   
1        0.0      0.0      0.0      0.0     0.0    0.0  0.0        0   
2        0.0      0.0      0.0      0.0     1.0    0.0  0.0        0   
3        0.0      1.0      0.0      0.0     0.0    0.0  0.0        0   
4        0.0      0.0      0.0      0.0     1.0    0.0  0.0        0   
...      ...      ...      ...      ...     ...    ...  ...      ...   
1381     0.0      0.0      0.0      0.0     0.0    1.0  0.0        0   
1382     0.0      0.0      0.0      0.0     1.0    0.0  0.0        0   
1383     0.0      0.0      0.0

In [ ]:
aggl_oscar = dfall_aggl[['cluster', 'Oscar Winners']]

In [ ]:
aggl_oscar

cluster  Oscar Winners
0           1              0
1           0              0
2           0              0
3           0              0
4           0              0
...       ...            ...
1381        0              0
1382        0              0
1383        0              0
1384        1              0
1385        0              0

[1386 rows x 2 columns]

In [ ]:
(aggl_oscar == 1).sum()

cluster          203
Oscar Winners     56
dtype: int64

In [ ]:
(aggl_oscar == 0).sum()

cluster          1183
Oscar Winners    1330
dtype: int64

In [ ]:
counter_0 = 0

for i, data in aggl_oscar.iterrows():
  cluster = aggl_oscar.at[i, 'cluster']
  oscar = aggl_oscar.at[i, 'Oscar Winners']

  if cluster == 1 and oscar == 1:
    counter += 1


counter

18

In [ ]:
aggl_genre = dfall_aggl[['romance', 'adventure', 'animation', 'western', 'mystery', 'comedy', 'biography', 'sports', 'family', 'thriller', 'documentary', 'sci-fi', 'crime', 'period', 'musical', 'history', 'fantasy', 'horror', 'drama', 'war', 'cluster']]

In [ ]:
aggl_genre

romance  adventure  animation  western  mystery  comedy  biography  \
0         0.0        0.0        0.0      0.0      0.0     0.0        0.0   
1         0.0        0.0        0.0      1.0      0.0     0.0        0.0   
2         0.0        0.0        0.0      0.0      0.0     0.0        0.0   
3         0.0        0.0        0.0      0.0      0.0     0.0        0.0   
4         0.0        0.0        0.0      0.0      0.0     0.0        0.0   
...       ...        ...        ...      ...      ...     ...        ...   
1381      0.0        0.0        0.0      0.0      0.0     0.0        0.0   
1382      0.0        0.0        0.0      0.0      0.0     0.0        0.0   
1383      0.0        0.0        0.0      0.0      0.0     0.0        0.0   
1384      0.0        1.0        0.0      0.0      0.0     0.0        0.0   
1385      0.0        1.0        0.0      0.0      0.0     0.0        0.0   

      sports  family  thriller  ...  sci-fi  crime  period  musical  history  \
0        0.0     0.0       0.0  ...     0.0    0.0     1.0      0.0      0.0   
1        0.0     0.0       0.0  ...     0.0    0.0     0.0      0.0      0.0   
2        0.0     0.0       0.0  ...     0.0    0.0     0.0      0.0      0.0   
3        0.0     0.0       0.0  ...     0.0    0.0     0.0      1.0      0.0   
4        0.0     0.0       0.0  ...     1.0    0.0     0.0      0.0      0.0   
...      ...     ...       ...  ...     ...    ...     ...      ...      ...   
1381     0.0     0.0       0.0  ...     0.0    0.0     0.0      0.0      0.0   
1382     0.0     0.0       0.0  ...     0.0    0.0     0.0      0.0      0.0   
1383     0.0     0.0       0.0  ...     0.0    0.0     0.0      0.0      0.0   
1384     0.0     0.0       0.0  ...     0.0    0.0     0.0      0.0      0.0   
1385     0.0     0.0       0.0  ...     0.0    0.0     0.0      0.0      0.0   

      fantasy  horror  drama  war  cluster  
0         0.0     0.0    0.0  0.0        1  
1         0.0     0.0    0.0  0.0        0  
2         0.0     1.0    0.0  0.0        0  
3         0.0     0.0    0.0  0.0        0  
4         0.0     1.0    0.0  0.0        0  
...       ...     ...    ...  ...      ...  
1381      0.0     0.0    1.0  0.0        0  
1382      0.0     1.0    0.0  0.0        0  
1383      0.0     0.0    1.0  0.0        0  
1384      0.0     0.0    0.0  0.0        1  
1385      0.0     0.0    0.0  0.0        0  

[1386 rows x 21 columns]